### ISSUE TITLE
Aircraft circle bigger when zoom

### ISSUE THREAD

**Issue by cesarpichon** [openscope/openscope#858] opened 2018-01-12 21:07 UTC
Browser: Google Chrome 62 / macOS Sierra

Airport: Everyone

Approximate play time before issue: 0sec

#### Issue Description

When we zoom in, the aircraft circle on the canvas become bigger. Can someone knows where the problem come from or know how to fix it ?

Thanks !

![](https://user-images.githubusercontent.com/5282262/34895178-ce610154-f7e4-11e7-8668-fcd3fd20a3b3.png)
![](https://user-images.githubusercontent.com/5282262/34895180-ce7b9bd6-f7e4-11e7-9617-2c4a8642b5cc.png)

#### Steps to reproduce

Just launch the program.

**Comment by erikquinn** [comment] 2018-01-12 21:47
This is actually by design. The dot represents the "primary radar return", meaning the area within which the radar is confident the aircraft is located (since there is some amount of error). Being a radar simulator first, this was an important improvement, though I agree it does look funny when zoomed all the way in on the airport. So at different zoom levels, the dot should take up the same amount of space relative to the markings on the scope.

**Comment by cesarpichon** [comment] 2018-01-12 23:35
All right I understand ! Thanks for your answer.

**Comment by erikquinn** [comment] 2018-01-13 01:29
Of course! :smiley: closing.

**Closed by erikquinn** 2018-01-13 01:29 UTC
Labels: invalid, wontfix
