### ISSUE TITLE
KSFO Flights not making Alt Restrictions on STARS

### ISSUE THREAD

**Issue by wmstapp** [openscope/openscope#1448] opened 2019-09-24 21:07 UTC
Browser: Chrome

Airport:  KSFO

Approximate play time before issue:  Re-Occuring

#### Issue Description
_please include any console errors and/or screenshots_ 
The following flights / Aircraft were not making altitude restrictions on the STARs resulting in having to vector around to burn off altitude before clearing for approach.  In addition these flight/Aircraft would go missed if not decended to 1500ft. before intercepting the localizer on at least a 10 mile final.

Flight: QXE4422
Aircraft: DH8D
STAR: INYOE.DYAMD5
Crossed FREELY @ FL175

DAL89
MD88
AMAKR.BEDGA3
Crossed BRIXX AT FL155

N5677Z
C510
INYOE.DYAMD5
Crossed FREELY @ FL144

HAL229
AT72
PAINT.PIRAT2
Crossed ARGGG @ FL110

QXE2283
DH8D
BDEGA3
Crossed BDEGA @ FL265
(This particular flight was almost out of airspace on the far SE side before it reached Airspace altitude to even give it a command)

DAL879
A321
DYAMD5
Crossed ARCHI @ 9000

#### Steps to reproduce
Play KSFO for any length of time, these instances will show up.

**Comment by erikquinn** [comment] 2019-09-26 00:22
Could be a case of aircraft being spawned at too high an initial altitude and being totally unable to meet their restrictions even when descending at their best rate. Will have to take a look and see if it's caused by that, or if they really are choosing not to start their descent when they should have already done so.

**Comment by wmstapp** [comment] 2019-09-26 18:32
Here's an example of an aircraft enter the scope area above airspace altitude.  I'm assuming it's on the BDEGA3 STAR - Aircraft is DH8D
![N38261](https://user-images.githubusercontent.com/45436083/65715082-09f55280-e062-11e9-8218-8ffeebd280f0.PNG)

**Comment by erikquinn** [comment] 2019-09-26 21:15
Yes, they are spawning far too high. Quick fix, here it comes

**Comment by erikquinn** [comment] 2019-09-26 21:19
@wmstapp See #1450 and the below link, where this issue should be fixed:

https://openscope-dev-pr-1450.herokuapp.com

**Comment by wmstapp** [comment] 2019-10-17 14:09
This is happening at KSFO with MD80 series and Dash 8's as well.

**Closed** 2019-10-17 16:09 UTC
Labels: BUGFIX, airport work, has pull request
