### ISSUE TITLE
force airportGuide links to open in new tab

### ISSUE THREAD

**Issue by n8rzz** [openscope/openscope#1322] opened 2019-02-07 19:52 UTC
AirportGuide content is generate html from markdown.  when airport guide content is loaded, there should be a method within `AirportGuideView` that looks at the content, grabs each `<a>` and adds a click handler to it.

Once we capture the click, we can add event tracking to the click and the link, then we can send the user on their way to the content loaded in a new tab:
```js
window.open(`${URL}`, '_blank');
```

**Comment by erikquinn** [comment] 2020-01-22 20:12
Accidentally made #1471 which essentially duplicates this issue. Don't see a significant need for event tracking, so will close this.

Closing as duplicate of #1471.

**Closed by erikquinn** 2020-01-22 20:12 UTC
Labels: invalid or duplicate
