### ISSUE TITLE
XXX leaving radar coverage without being cleared to XXX

### ISSUE THREAD

**Issue by Pyw2003** [openscope/openscope#477] opened 2017-05-21 01:37 UTC
Every departure flight shows "XXX leaving radar coverage without being cleared to XXX", how to solve?

**Comment by n8rzz** [comment] 2017-05-21 01:58
@Pyw2003 what airport are you seeing this at?

This is very possibly related to #475

**Comment by Pyw2003** [comment] 2017-05-21 02:04
I saw this problem at several airports and now is EDDH

**Comment by Pyw2003** [comment] 2017-05-21 02:07
@n8rzz I would like to ask how can I download this simulator to my computer to play offline?

**Comment by n8rzz** [comment] 2017-05-21 02:08
Are you seeing this same issue on an airport like `ksfo`?  At the airports where you are seeing this, is the last waypoint in the SID inside controlled airspace?  Or are the aircraft still working through the SID waypoints when they exit the airspace?

**Comment by n8rzz** [comment] 2017-05-21 02:08
for running locally, we have a walkthrough for that: https://github.com/openscope/openscope/tree/develop/tools

**Comment by n8rzz** [comment] 2017-05-21 02:09
you can also join us on slack (http://slack.openscope.co) if you have questions getting set up.  Someone is usually on or available to field questions and it's faster then issue comments.

**Comment by Pyw2003** [comment] 2017-05-21 02:17
@n8rzz No this problem happen in KSFO, the aircraft still working through the SID waypoints when they exit the airspace. Also, I do not quite understand which files to open running locally, I have downloaded all the files and NodeJS.

**Comment by n8rzz** [comment] 2017-05-21 02:20
did you also run `npm install` and `npm run build`?  After that you can run `npm run start` and then in a web browser navigate to `localhost:3003`

You should really join us on slack, it'll be much faster to get you up and running.

**Comment by Pyw2003** [comment] 2017-05-21 02:26
@n8rzz 

Your environment has been set up for using Node.js 7.10.0 (x64) and npm.

C:\Users\12713>npm install
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\12713\package.json'
npm WARN 12713 No description
npm WARN 12713 No repository field.
npm WARN 12713 No README data
npm WARN 12713 No license field.

C:\Users\12713>npm run build
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! path C:\Users\12713\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\12713\package.json'
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\12713\package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\12713\AppData\Roaming\npm-cache\_logs\2017-05-21T02_26_47_311Z-debug.log

C:\Users\12713>npm run start
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! path C:\Users\12713\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\12713\package.json'
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\12713\package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\12713\AppData\Roaming\npm-cache\_logs\2017-05-21T02_26_57_359Z-debug.log

**Comment by n8rzz** [comment] 2017-05-21 02:32
is `12713` the project folder?  You will also need git installed, if you don't have that already.

from nothing to running should be the following:
- `git clone http://github.com/openscope/opscope.git`
- `cd openscope/`
- `npm install`
- `npm run build`
- `npm run start`

after that, you should be able to navigate to `localhost:3003` in a web browser to view the app.

**Comment by Pyw2003** [comment] 2017-05-21 02:53
@n8rzz How to run `git clone http://github.com/openscope/opscope.git` and `cd openscope/`?

C:\Users\12713\Desktop\openscope-develop>npm install
npm WARN deprecated gulp-minify-css@1.2.4: Please use gulp-clean-css
npm ERR! git clone --template=C:\Users\12713\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:jonschlinkert/micromatch.git C:\Users\12713\AppData\Roaming\npm-cache\_git-remotes\git-github-com-jonschlinkert-micromatch-git-2-2-0-c0994e2c: undefined
npm ERR! git clone --template=C:\Users\12713\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:jonschlinkert/micromatch.git C:\Users\12713\AppData\Roaming\npm-cache\_git-remotes\git-github-com-jonschlinkert-micromatch-git-2-2-0-c0994e2c: undefined
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ENOGIT

npm ERR! not found: git
npm ERR!
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\12713\AppData\Roaming\npm-cache\_logs\2017-05-21T02_46_47_310Z-debug.log

**Comment by n8rzz** [comment] 2017-05-21 03:03
you will need to install `git` first.  https://git-scm.com/book/en/v2/Getting-Started-Installing-Git

npm uses git under the hood, so if you don't have it installed you can't download what you need.

**Comment by Pyw2003** [comment] 2017-05-21 03:23
@n8rzz 
 
I entered `git clone http://github.com/openscope/opscope.git` and login, but failed.

```
$ git clone http://github.com/openscope/opscope.git
Cloning into 'opscope'...
remote: Repository not found.
fatal: repository 'https://github.com/openscope/opscope.git/' not found
```

**Comment by n8rzz** [comment] 2017-05-21 03:24
you missed the `en` in `openscope.git`.

`https://github.com/openscope/openscope.git`

**Comment by Pyw2003** [comment] 2017-05-21 03:36
@n8rzz 

```
$ git clone http://github.com/openscope/openscope.git
Cloning into 'openscope'...
warning: redirecting to https://github.com/openscope/openscope.git/
remote: Counting objects: 26698, done.
remote: Compressing objects: 100% (90/90), done.
remote: Total 26698 (delta 46), reused 75 (delta 25), pack-reused 26582
Receiving objects: 100% (26698/26698), 13.63 MiB | 872.00 KiB/s, done.
Resolving deltas: 100% (17540/17540), done.
```
Then run `npm install` in Node.js but failed.
```
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ENOGIT

npm ERR! not found: git
npm ERR!
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\12713\AppData\Roaming\npm-cache\_logs\2017-05-21T03_33_35_404Z-debug.log
```

It is too difficult for non-professionals like me to install, (⊙﹏⊙)b

**Comment by n8rzz** [comment] 2017-05-21 03:44
try closing and re-opening your cmd window.  If you installed git with it open, it is likely that your terminal is still unaware of gits existence.

yep, it is hard.  but that's ok.  it was hard once for us professionals too.  we just do it a lot more, so these things are easy for us.  I'm here to help (for the next hour).

you should really join our slack channel.  this type of thing goes much quicker over chat than it does here.

**Comment by n8rzz** [comment] 2017-05-21 03:46
also, be sure to `cd` into the `openscope` directory before running any of the `npm` commands

**Comment by Pyw2003** [comment] 2017-05-21 03:46
@n8rzz So how can I join your slack channel? Thanks for your help!

**Comment by n8rzz** [comment] 2017-05-21 03:47
http://slack.openscope.co

enter your email and follow the instructions

**Comment by georgeenciu** [comment] 2017-05-22 07:49
Had the same problem on `feature/206` branch: 

![image](https://cloud.githubusercontent.com/assets/1264087/26297558/faf6e520-3edb-11e7-928c-09199c94d6ca.png)

`BAW365` is cleared to `BUKEL`

![image](https://cloud.githubusercontent.com/assets/1264087/26297578/29a71552-3edc-11e7-9122-b79702d93500.png)

**Closed** 2017-06-01 23:36 UTC
Labels: has pull request, refactor

**Comment by kaitsu71** [comment] 2020-10-21 11:20
I started to get this now for some reason at EDDL for the aircarft arriving from east. Just as before I say: <aircarft> c 20 fh 270 and soon I get leaving radar coverage error.

**Comment by Fechulo** [comment] 2020-10-21 13:21
Hey @kaitsu71 That's working as intended since #1307 . The floor of the airspace section to the East is FL65, so aircraft below that will be outside your airspace. You can turn on the airspace depiction via the scope options menu
