### ISSUE TITLE
KLAS needs an update

### ISSUE THREAD

**Issue by panther2** [openscope/openscope#485] opened 2017-05-23 19:04 UTC
I just noticed some SIDs being either renamed or missing. Also not all STARs appear to be coded...

I will be happy to update it accordingly, as soon as I find some time to do it.

**Comment by indianbhaji** [comment] 2017-05-23 20:25
All airports need updates, it's just a case of keeping on top of them

**Comment by panther2** [comment] 2017-05-23 21:33
So no issue?

**Comment by indianbhaji** [comment] 2017-05-23 21:34
Keep the issue, but do you have access to zube.io?

**Comment by panther2** [comment] 2017-05-23 21:36
Yes...

**Comment by indianbhaji** [comment] 2017-05-23 21:37
Go to epics and then "update airports to the latest airac", @erikquinn suggested that we could keep airport update issues in there so we don't get an overload in issues here

**Comment by panther2** [comment] 2017-05-23 21:40
OK, it is more or less a blackbox to me. I did not know that. 
I have no problem to close that issue here.

**Comment by panther2** [comment] 2017-05-23 21:52
@indianbhaji 

I don't understand that... there are issues behind each card, for example Brussels is #178 ?
EDDF is  #199 - so what is the point?

**Comment by indianbhaji** [comment] 2017-05-23 23:09
Those issues were made before the epic was made and since they already have PRs attached there is no point closing them

Outdated airport information is an ongoing issue, by using an epic we can easily see what needs to be updated. Since issues in an epic do not actually create an issue on github, it helps clean up the repo up by not cluttering the issues on github with pretty much the same things, just like the airport revivals that were opened a while ago

**Comment by erikquinn** [comment] 2017-05-24 00:29
@panther2 If this is in progress, would you mind opening up a pull request for it? You can just mark the PR as `WIP`, and when you're all done with it just request a review. 😃

**Comment by panther2** [comment] 2017-05-24 06:32
Thank you @indianbhaji for explaining that to me.
And I will do that @erikquinn .

Just one additional question for future other airport updates, as I was told to only create PRs that have a corresponing issue on github, and I want to do it correctly then:
What will I be referencing when there is "only" another 'card' in  epic and no issue on github? 
Would I name the PR as for example `feature/EPIC#XYZ`, `XYZ` being the number of the card in ZUBE?

**Comment by erikquinn** [comment] 2017-05-25 01:10
@panther2 Far less complicated than that. Sometimes we use epics to track the progress of a "goal" that will take many pull requests to complete. But at the simplest level, there is one github issue (this one, 485) that maps to one pull request that resolves that issue. And depending on whether this issue is a `bug` or `feature` determines the prefix. Since this is not a bugfix, we would use a branch name of `feature/485`, and use that in the title of the pull request. I see you've got it all done correctly. :+1:

**Comment by panther2** [comment] 2017-06-26 19:28
@n8rzz @erikquinn 

Just a notice that I am still willing to go on with this and #487.
At the moment I just feel sort of overhelmed by all the changes/modifications that are underway.
So I am just waiting for a sort of "consolidation" in the airport-format, airport-file-standards and probably other doc files, that I really do need as orientation to not get further lost.

**Comment by n8rzz** [comment] 2017-06-26 20:23
Both files should be pretty stable now.  The repo will be in a constant state of change, but the standards called out in those docs should be accurate despite any upcoming changes. For the near future anyway.

**Comment by panther2** [comment] 2017-06-26 21:43
@n8rzz 

I think I am more or less referring to the issues I stumbled over when doing EDDL ( #403 ) and that we discussed on Slack, starting mid-May. Some of them I remember to be open concerning a solution or documentation:

- discussion about multi runway suffixes and spawnpattern implications
- #32  related implications
- ranged altitude and speed restrictions
- issue #430

To me it's sometimes hard to identify solutions just by issues/PRs so I hoped for added documentation ...

But maybe I'm thinking too complicated and should just move on... :wink:

**Comment by n8rzz** [comment] 2017-06-26 22:50
Well, the good news is #s 2 & 3 on your list are done/nearing completion. 

The other two have not been started yet. I would say, though, don't let that hold you back. Pick one of those airports and go for it!

**Comment by panther2** [comment] 2017-08-17 07:49
I will not be able to start working on this anytime soon, as I am still struggeling with EDDL (#403) (evaluation spawn patterns, geo stuff, understanding new requirements... ) and my time at the moment is quite restricted.

So if anyone feels that this issue should have a higher priority, feel free to join or take over the task.
Thank you. :smile:

**Comment by erikquinn** [comment] 2017-08-17 15:29
@panther2 No worries! I'll just unassign you so it appears to be available if anybody wants to take it on in the meantime. :smiley:

**Comment by erikquinn** [comment] 2017-08-23 14:43
Also to the taker of this task, be advised Runways 7L-25R and 7R-25L have been renamed to 8L-26R and 8R-26L!

**Comment by panther2** [comment] 2017-09-16 20:35
Thanks for taking care, @Fechulo .

**Comment by Fechulo** [comment] 2017-09-16 20:39
No worries 😄

**Closed** 2017-11-28 22:50 UTC
Labels: airport work, has pull request, refactor
