### ISSUE TITLE
Too-low glidelope intercept messages not showing

### ISSUE THREAD

**Issue by wmstapp** [openscope/openscope#1242] opened 2018-11-28 21:04 UTC
Browser: chrome

Airport: KMIA

Approximate play time before issue:  random

#### Issue Description
_please include any console errors and/or screenshots_ 
Some aircraft will consistently go missed.  I have tried reroutes, different runways and approaches as well as different GS intercept altitudes; however, they still consistently will go missed.  I have noticed the issue predominantly with MD80 series aircraft (82 and 83) also had one instance with an E190.  

#### Steps to reproduce
-

**Comment by Fechulo** [comment] 2018-11-28 21:16
It's very likely that they're simply too high to intercept the glideslope. MD80s and Embraers have pretty slow descent rates so that seems like the most likely explanation

**Comment by wmstapp** [comment] 2018-11-28 21:41
I've put them on 15+mile intercept at 2000 ft. - much further back than the D11.1 mile intercept point which is 3000 ft. on the published charts.  I've tried multiple different altitudes (lower than on the published charts) at multiple different distances (further than on the published charts).   I can try bringing them in even lower on the GS intercept and report back.  ¯\_(ツ)_/¯

**Comment by felixscheffer** [comment] 2018-11-28 22:40
Very likely a duplicate of #1084. Can you please try a higher altitude, for example, 3000 ft?

You can also check out the latest and greatest version of openScope at http://dev.openscope.co/

**Comment by erikquinn** [comment] 2018-11-28 22:50
Hm... as of #1146 being merged, you should be getting a warning:
`unable ILS ${runwayModel.name}, our assigned altitude is below the minimum glideslope intercept altitude, request climb to ${minimumGlideslopeInterceptAltitude}`

Perhaps a change since then has already broken them? :confused:

They are supposed to reject the approach clearance altogether if they're too low like that.

**Comment by felixscheffer** [comment] 2018-11-28 23:06
@erikquinn  #1146 is still unreleased. It's part of the upcoming 6.8.0 release.

**Comment by wmstapp** [comment] 2018-11-28 23:58
@erikquinn  I was not getting a below min alt error. 
@felixscheffer  I will try intercepting at 3000.  And I will definitely check out the Beta version.
I was able to get them to land by putting them on a 15+ mile final at 1500ft. 

BTW, I love the sim!  Great work! I've paid for a couple of ATC simulators and this one is by far the most in depth.  Thanks!

**Comment by felixscheffer** [comment] 2018-11-29 00:02
@wmstapp  Feel free to join us on slack. http://slack.openscope.co/

**Comment by erikquinn** [comment] 2018-11-29 00:11
@felixscheffer Yep, I meant we should be seeing it on develop (or staging)-- but we actually aren't. All we get is the go around message.

**Comment by felixscheffer** [comment] 2018-11-29 00:31
@erikquinn Then there is something wrong here. Can you look into it?

**Comment by felixscheffer** [comment] 2018-11-30 12:22
The message is definitely not shown on staging.

**Comment by wmstapp** [comment] 2018-11-30 17:36
So, I tried bringing the AC in on a 20+mile final at 3000 and still am getting missed approaches.  The only way I've been able to get them to land is to bring them in on a 20+mile final at 1500.

**Comment by Fechulo** [comment] 2018-11-30 19:05
I can't seem to reproduce it. Could you maybe record a video or a gif or even post screenshots of the situation and the commands you're typing?

**Comment by erikquinn** [comment] 2018-12-01 04:13
I saw a few. I went specifically to miami, and an E135 went missed. Not sure what the issue is though.

**Comment by wmstapp** [comment] 2018-12-01 04:36
I’ll see what I can do to make a video. I’m currently traveling with just my laptop. I have FRAPS on my desktop at home- May have to wait til I go back home.   It appears to be specific to MD 82/83 & ERJ135/145

**Comment by Fechulo** [comment] 2018-12-01 08:37
@erikquinn could it possibly be that their descent rates are too slow to keep up with the glideslope?

**Closed** 2019-01-01 21:40 UTC
Labels: BUGFIX, has pull request
