### ISSUE TITLE
Airlines using "ILS" landing procedure

### ISSUE THREAD

**Issue by devman0903** [openscope/openscope#363] opened 2017-04-24 12:59 UTC
ILS has been very glitchy. Running the ILS command makes the airline go off the radar / re-routes planes away from the radar

I will submit screenshots when the game is back up "if not fixed by then"

**Comment by n8rzz** [comment] 2017-04-24 13:16
Could you provide some steps to reproduce this one?

- airport
- command(s) issued
- any console errors present after the command was issued

**Comment by devman0903** [comment] 2017-04-24 13:21
it may take a while. will you be on later.

**Comment by devman0903** [comment] 2017-04-24 13:22
i gotta go

**Comment by devman0903** [comment] 2017-04-24 13:22
will comment the specs later

**Comment by n8rzz** [comment] 2017-04-24 13:22
You could also head on over to slack.openscope.co if you want some faster debugging help 😉 

Sounds good!

**Comment by n8rzz** [comment] 2017-04-24 13:24
ahh, and yes.  I'm on most of the time (easier to reach me via slack)

**Comment by erikquinn** [comment] 2017-06-27 00:45
Closing as duplicate of #38.

**Closed by erikquinn** 2017-06-27 00:45 UTC
Labels: invalid
