### ISSUE TITLE
Add restricted section to airport-format document

### ISSUE THREAD

**Issue by n8rzz** [openscope/openscope#520] opened 2017-06-14 12:18 UTC
Seems we are missing this section of the airport documentation.

**Comment by erikquinn** [comment] 2017-06-14 21:26
And airways.

**Comment by ij1** [comment] 2017-06-15 19:54
> And airways.

???

Airways are already in the documentation (both in the example block and descriptive part).

**Comment by erikquinn** [comment] 2017-09-03 19:05
Closing as duplicate of #452.

**Closed by erikquinn** 2017-09-03 19:05 UTC
Labels: documentation
