### ISSUE TITLE
KJFK can't play

### ISSUE THREAD

**Issue by ghariman** [openscope/openscope#1586] opened 2020-05-19 04:06 UTC
Browser: Chrome/Edge

Airport: KJFK

Approximate play time before issue: immediately

#### Issue Description
As soon as select KJFK from list of airports, then nothing happens. Can't play KJFK

#### Steps to reproduce
- Select KJFK from the airport menu, then problem will be seen

**Comment by Fechulo** [comment] 2020-05-19 12:26
This is fixed by [bugfix/1573](https://github.com/openscope/openscope/pull/1574)

**Comment by Fechulo** [comment] 2020-05-19 12:26
Closing as a duplicate of #1573

**Closed by Fechulo** 2020-05-19 12:26 UTC
