### ISSUE TITLE
Departing aircraft disappears then reappears after departure on EDDM

### ISSUE THREAD

**Issue by panther2** [openscope/openscope#194] opened 2017-01-30 16:50 UTC
Experienced minutes ago:
![chrome_2017-01-30_17-46-19](https://cloud.githubusercontent.com/assets/20812775/22432138/37ce2ba4-e714-11e6-865f-3625f9c9ce70.png)

**Comment by indianbhaji** [comment] 2017-01-30 16:52
That's normal, and I remember @n8rzz saying that this is something that allows us to know about what needs to be worked on. München is going for a rework anyways (soon)

**Comment by panther2** [comment] 2017-01-30 16:57
OK , thanks... down't know if this is related to this issue, but I experienced a starting plane that was cleared via the ALG exit... it disappeared after about 10 nm (adding 10 to the points balance)... respawned seconds ago still following the course... and giving another 10 points when leaving the radar scope.

**Comment by indianbhaji** [comment] 2017-01-30 17:00
@panther2 Yeah, I don't think that's got anything to do with the airport file itself, @n8rzz might be interested in this though!

**Comment by panther2** [comment] 2017-01-30 17:04
... and while typing this, I am still waiting for the second plane to start and the first plane to arrive...
Sim has been running for 20 minutes now...

**Comment by indianbhaji** [comment] 2017-01-30 17:05
@panther2 Yeah, you'll be waiting a while for aircraft. The spawn rate is highly unrealistic for EDDM in the game.

**Comment by panther2** [comment] 2017-01-30 17:29
... yes, I used timewarp then... and about one hour later two arrivales occurred, but no second departure :-)

**Comment by n8rzz** [comment] 2017-01-30 19:44
@panther2 
>I don't know if this is related to this issue, but I experienced a starting plane that was cleared via the ALG exit... it disappeared after about 10 nm (adding 10 to the points balance)... respawned seconds ago still following the course... and giving another 10 points when leaving the radar scope.

Could you explain this a little more.  What exactly happened here?  Did the plane just disappear?

**Comment by panther2** [comment] 2017-01-30 20:55
@n8rzz 

These were the commands I gave:
- ID w
- ID caf
- ID to
- ID cvs

About 10-15 nm after the start, the plane issued "München Radar, ID, switching to center, good day" (adding 10 Points) and became invisible for some seconds. Then it respawned and took it's course via the ALG exit. It ended adding another 10 points to my balance.

**Comment by n8rzz** [comment] 2017-01-30 21:20
you didn't get the memo about 2x points monday?  kidding.

This does seem curious.  I'll keep an eye out for this and see what we can find.  I'm going to re-title this issue targeting this issue.  

If you see it again, please post back here with any more detail.

**Comment by panther2** [comment] 2017-01-30 21:21
Will do.

**Comment by panther2** [comment] 2017-01-30 21:52
@n8rzz 

I have been able to reproduce it on the ALG departure (seems to occur only there).
However, the plane does not disappear from the radar and respawn, but the aircarft strip.

Enjoy the video:
![16](https://cloud.githubusercontent.com/assets/20812775/22443285/aaf64cae-e73e-11e6-935f-19ed98427cd4.gif)

**Comment by n8rzz** [comment] 2017-01-30 22:27
@panther2 when the aircraft disappears, does it climb to 10,000ft and stay there?  Even after reappearing?

**Comment by n8rzz** [comment] 2017-01-30 22:30
The first part, it is leaving the airspace because it has reached the airspace ceiling and is actually leaving.

My hunch, is math.  Even though it is displayed as 10,000 I'm guessing that it is not.  It's like 9999.999999999 or something.

**Comment by Fechulo** [comment] 2017-01-30 22:53
@n8rzz I think it's a different issue going on here. The aircraft is climbing above FL100 and when it reaches FL112 it starts descending once again to FL100 en re-enters the airspace. This could be happening due to the altitude restrictions in the airport file, but I'm looking at it now and nothing should be causing it to descend again.

When the aircraft is cleared as filed, the target altitude is set to FL070, as this is the initial climb for SID's at EDDM. The aircraft is then told to climb via the SID and the target altitude increases to FL100. The first fix in the SID has no altitude restrictions, just a speed restriction (not written correctly, which could possibly be the cause of this bug). Once the aircraft flies over the first fix, the target altitude is set to FL430 (the max cruise level).

The second fix in the SID must be flown at or above FL070 so the aircraft continues climbing and leaves the airspace at FL100 (airspace ceiling). Once it flies over this second fix, the target altitude is reset to FL100, even though the next fix has no restrictions. 

My take on the issue:
Theory 1) The misspelled speed restrictions may be breaking everything and confusing the aircraft.
Theory 2) When a fix doesn't have a restriction, it is given an airspace ceiling restriction by default. Even though the third fix in the SID has no restrictions, the game may be adding an invisible altitude restriction of FL100.

**Comment by panther2** [comment] 2017-01-31 13:31
@n8rzz 

> when the aircraft disappears, does it climb to 10,000ft and stay there? Even after reappearing?

Watching again the full size video I can confirm what @Fechulo stated

> ... The aircraft is climbing above FL100 and when it reaches FL112 it starts descending once again to FL100 en re-enters the airspace. ...

After takeoff the plane indeed climbed until FL112. The aircraft strip disappeared at FL100. After reaching FL112 the plane started descending to FL100. At FL100 the aircraft strip reappeared. The plane stayed at FL100 until it reached the radar scope and started further climbing then.

**Comment by erikquinn** [comment] 2017-02-05 02:32
@Fechulo hit the nail on the head:

>Theory 2) When a fix doesn't have a restriction, it is given an airspace ceiling restriction by default. Even though the third fix in the SID has no restrictions, the game may be adding an invisible altitude restriction of FL100.

Related: #32.

**Comment by erikquinn** [comment] 2017-04-14 14:27
No longer observed for `ALG` departure at `EDDM`. However, the issue may still exist. Need to verify that aircraft will not overclimb their next restriction if they have a lot of time to their first fix that has NO restriction, and then their next one has a restriction that is now below their current altitude.

**Comment by erikquinn** [comment] 2017-04-14 16:58
Bug still present.

**Comment by erikquinn** [comment] 2017-07-04 02:08
Resolved by #525 (feature #32). Closing.

**Closed by erikquinn** 2017-07-04 02:08 UTC
Labels: BUGFIX
