### ISSUE TITLE
EGLL contains a spawnPattern with a routeString set as the destination

### ISSUE THREAD

**Issue by devman0903** [openscope/openscope#362] opened 2017-04-24 12:55 UTC
Hello, I am having a problem "i assume" about loading the game directory. The game is stuck at splash-screen.gif

I cant upload right now

**Comment by n8rzz** [comment] 2017-04-24 12:56
what browser are you using?

**Comment by devman0903** [comment] 2017-04-24 13:00
Chrome 57

**Comment by n8rzz** [comment] 2017-04-24 13:02
hmmm 🤔 

Well thats odd.  What happens if you click the loading screen (odd, I know, but give that a shot)?

**Comment by devman0903** [comment] 2017-04-24 13:02
THe game was working 'till this morning

**Comment by devman0903** [comment] 2017-04-24 13:02
still stays stuck when clicked

**Comment by n8rzz** [comment] 2017-04-24 13:03
also try in incognito mode if that doesn't work.  I am also using chrome 57 and it's working for me.

**Comment by devman0903** [comment] 2017-04-24 13:03
not working

**Comment by devman0903** [comment] 2017-04-24 13:04
wait, im about to restart chrome

**Comment by devman0903** [comment] 2017-04-24 13:04
still stuck

**Comment by n8rzz** [comment] 2017-04-24 13:05
are there any errors in the console?  `ctrl+alt+i` and click console tab. or `cmd+alt+i` if you're on a mac

**Comment by devman0903** [comment] 2017-04-24 13:07
Errors

The 'CPT' procedure does not contain exitPoints or entryPoints. If this is a SID, at least one exitPoint must be defined. If this is a STAR, at least one entryPoint must be defined.
value @ StandardRouteModel.js:354
StandardRouteModel.js:354 The 'BPK' procedure does not contain exitPoints or entryPoints. If this is a SID, at least one exitPoint must be defined. If this is a STAR, at least one entryPoint must be defined.
value @ StandardRouteModel.js:354
StandardRouteModel.js:354 The 'WOBUN' procedure does not contain exitPoints or entryPoints. If this is a SID, at least one exitPoint must be defined. If this is a STAR, at least one entryPoint must be defined.
value @ StandardRouteModel.js:354
StandardRouteModel.js:354 The 'BUZAD' procedure does not contain exitPoints or entryPoints. If this is a SID, at least one exitPoint must be defined. If this is a STAR, at least one entryPoint must be defined.
value @ StandardRouteModel.js:354
StandardRouteModel.js:354 The 'DET' procedure does not contain exitPoints or entryPoints. If this is a SID, at least one exitPoint must be defined. If this is a STAR, at least one entryPoint must be defined.
value @ StandardRouteModel.js:354
StandardRouteModel.js:354 The 'GOGSI' procedure does not contain exitPoints or entryPoints. If this is a SID, at least one exitPoint must be defined. If this is a STAR, at least one entryPoint must be defined.
value @ StandardRouteModel.js:354
StandardRouteModel.js:354 The 'GASGU' procedure does not contain exitPoints or entryPoints. If this is a SID, at least one exitPoint must be defined. If this is a STAR, at least one entryPoint must be defined.
value @ StandardRouteModel.js:354
StandardRouteModel.js:354 The 'MAY' procedure does not contain exitPoints or entryPoints. If this is a SID, at least one exitPoint must be defined. If this is a STAR, at least one entryPoint must be defined.
value @ StandardRouteModel.js:354
StandardRouteModel.js:354 The 'MID' procedure does not contain exitPoints or entryPoints. If this is a SID, at least one exitPoint must be defined. If this is a STAR, at least one entryPoint must be defined.
value @ StandardRouteModel.js:354
LegModel.js:406 Uncaught TypeError: Cannot read property 'toWaypointModel' of null
    at LegModel.value (LegModel.js:406)
    at LegModel.value (LegModel.js:385)
    at LegModel.value (LegModel.js:224)
    at new LegModel (LegModel.js:126)
    at Fms.value (Fms.js:1070)
    at Fms.js:1052
    at arrayMap (_arrayMap.js:16)
    at map (map.js:50)
    at Fms.value (Fms.js:1051)
    at Fms.value (Fms.js:313)
App.js:347 Uncaught TypeError: Cannot read property 'canvas_complete' of null
    at App.value (App.js:347)
    at App.value (App.js:379)
    at App.js:437

**Comment by n8rzz** [comment] 2017-04-24 13:10
<img width="649" alt="screen shot 2017-04-24 at 8 10 00 am" src="https://cloud.githubusercontent.com/assets/3325985/25338617/770c26ca-28c5-11e7-924c-106001d2862e.png">

try navigating to the `application` tab and clearing out the localStorage values for openscope.

**Comment by devman0903** [comment] 2017-04-24 13:10
London international (i think)

**Comment by devman0903** [comment] 2017-04-24 13:14
Awesome, It worked, Thanks, can you look at this issue  #363 
![screenshot 2017-04-24 at 08 11 41](https://cloud.githubusercontent.com/assets/17048104/25338717/cd385604-28c5-11e7-8e04-ae23180eb6f7.png)

**Comment by n8rzz** [comment] 2017-04-24 13:15
this is a result of an invalid `destination` set in the airport file.  the (or the first) offending route is for `EGLL.BPK.BPK`.  this is should be set as the `routeString` and not the `destination`.

Good find!

**Comment by devman0903** [comment] 2017-04-24 13:16
Anything to get this awesome project up and running again

**Comment by devman0903** [comment] 2017-04-24 13:17
head over to #363

**Comment by n8rzz** [comment] 2017-04-24 13:17
purring like a kitten now, it seems 😉

**Comment by n8rzz** [comment] 2017-04-24 13:34
Invalid spawnPatterns are for the following routes:
- `EGLL.WOBUN.WOBUN`
- `EGLL.BPK.BPK`

**Comment by Fechulo** [comment] 2017-04-25 10:59
I think all the spawnPatterns for SID's are throwing errors since none of them have exitPoints.

**Comment by n8rzz** [comment] 2017-04-25 11:15
that is possible too.  but because of the two offending patterns above, the airport doesn't load at all.

**Comment by indianbhaji** [comment] 2017-04-27 15:35
Will assign myself when I get home but the issue is that the `destination` is set to `EGLL.WOBUN.WOBUN` whereas the route string is empty. Heathrow needs to go for a rework anyways as the SIDs look outdated

**Comment by indianbhaji** [comment] 2017-05-24 09:55
Fixed through https://github.com/openscope/openscope/commit/084725606df2502352969ae83ad5614da4b22952, closing!

**Closed by indianbhaji** 2017-05-24 09:55 UTC
Labels: airport work, BUG
