### ISSUE TITLE
Aircraft Rate of Descent

### ISSUE THREAD

**Issue by doofus** [openscope/openscope#1228] opened 2018-11-25 15:50 UTC
https://github.com/openscope/openscope/blob/f3395aef504318e22a8ba1d80b87ef37ce9e78f4/assets/aircraft/e135.json#L17

I wonder if this rate of descent is too low.  When playing the sim I always dread having an E135 as they take so long to reach a low enough altitude to land properly.  If I put this aircraft on the place and speed on the glidescope as a CR2 (a comparable aircraft), then it will miss the approach.  There are also times when a E135 will spawn at over FL200 and then exit the area at FL150+.  You get penalized, but since it never got down to FL140 you are never able to issue commands to it.

Unfortunately, the online sources of performance data show a rate of descent of 1500 ft/min.  However this value makes this aircraft unplayable at times.

**Comment by Marcel510** [comment] 2018-11-25 21:44
The problem with the rates is that they are in fpm, a descent rate is dependent to the speed the aircraft is flying at the moment most of the speeds are really unrealistic which worsens it even more. See: #965 & #977

**Comment by erikquinn** [comment] 2020-02-09 13:36
Closing as duplicate of the newer bug #1398. The problem will be worked from there instead.

**Closed by erikquinn** 2020-02-09 13:36 UTC
Labels: invalid or duplicate
