### ISSUE TITLE
Runway unusable for departures after re-taxi

### ISSUE THREAD

**Issue by Marcel510** [openscope/openscope#1067] opened 2018-08-24 16:52 UTC
_There might already be an issue for this_  

Airport: EDDF (affects all airports)

#### Issue Description
When you taxi an aircraft to the wrong runway accidentally and therefore re-taxi it to the correct runway, the other runway gets unusable.

#### Steps to reproduce
at EDDF:
- Taxi an aircraft to runway 25C
- Taxi the same aircraft to runway 18
- Taxi another aircraft to runway 25C    
----
- Now you won't see the second aircraft on the radar screen and you can't clear the aircraft for takeoff.
- When you clear the aircraft for takeoff this error appears:
![screenshot_126](https://user-images.githubusercontent.com/24833249/44597045-a8afdf80-a7ce-11e8-9d28-c5db29d18cae.png)

**Comment by felixscheffer** [comment] 2018-08-24 16:55
duplicate of #870

**Closed** 2018-08-24 16:57 UTC
Labels: BUGFIX
