### ISSUE TITLE
MIssed Approach 

### ISSUE THREAD

**Issue by Casp959er73** [openscope/openscope#1399] opened 2019-06-06 13:03 UTC
Browser: Chrome 

Airport: Literally every airport

Approximate play time before issue: Throughout the whole game 

#### Issue Description
Whenever I clear a plane for the ils they intercept it but just before the land they announce that they are going missed approach and I have to redirect them to the runway. They then to the same thing. 
_please include any console errors and/or screenshots_ 
<img width="1680" alt="Screen Shot 2019-06-06 at 15 01 23" src="https://user-images.githubusercontent.com/51446977/59034748-1152df00-886c-11e9-8e3c-d576031e9439.png">

#### Steps to reproduce
- Vector in aircraft by rerouting
- Adjust speeds
- Just as they are on final clear them to land by using the ils runway command.

**Comment by riyaadazad** [comment] 2019-07-16 14:00
As per your screenshot, it seems as if you are clearing aircraft too late. This happens to me occasionally as well. Make sure you clear aircraft at least 2 range rings from the runway. This technique usually solves my issue.

**Comment by erikquinn** [comment] 2019-07-19 01:55
Hi @Casp959er73 and @riyaadazad. There do seem to be some fairly serious issues with aircraft climbing on short final for no reason-- we're using issue #1395 to track the work on this. To avoid duplication, I'll close this, and you are welcome to add to that issue with any details you have on the problem.

Thanks! Closing as duplicate of #1395.

**Closed by erikquinn** 2019-07-19 01:55 UTC
