### ISSUE TITLE
Departure Aircraft Missing

### ISSUE THREAD

**Issue by Aviation34L** [openscope/openscope#1651] opened 2020-10-09 23:04 UTC
Browser: Chrome

Airport: CYHZ, CYOW, EGGW, EICK, LIPZ, LROP

Approximate play time before issue: When starting

Issue Description
When opening up any of the listed airports, all departure aircraft say they are leaving the airspace without being on their route. The score is also reduced by 25 for each aircraft.

![Screenshot 2020-10-09 at 5 00 11 PM](https://user-images.githubusercontent.com/72633120/95638235-1d970f80-0a51-11eb-9bc4-1a22908ddb0e.png)

Steps to reproduce
Open up openScope and select one of the previously mentioned airports.

**Comment by Fechulo** [comment] 2020-10-09 23:11
Yep, we're aware of the issue. Thanks for compiling the list, I think there may be a couple more working incorrectly. This is caused by an issue related to #1307 and should be fixed soon

**Comment by Fechulo** [comment] 2020-10-20 22:35
LIPZ fixed by @Fratee in #1659 
EICK (+ EINN & EIDW) fixed by me in #1653 
I will open a PR shortly to address the remaining broken airports

**Closed** 2020-10-30 00:46 UTC
Labels: airport work, has pull request, refactor
