### ISSUE TITLE
KLAX: Expand airspace to include the entirety of GOATZ/DIRBY/LEENA/etc STARs

### ISSUE THREAD

**Issue by ghariman** [openscope/openscope#1587] opened 2020-05-19 04:11 UTC
Browser: chrome/edge

Airport: KLAX

Approximate play time before issue: 5 minutes

#### Issue Description
_please include any console errors and/or screenshots_ 
![image](https://user-images.githubusercontent.com/17579182/82283641-cf6f5b80-994b-11ea-9601-fd330126a089.png)

![image](https://user-images.githubusercontent.com/17579182/82283739-16f5e780-994c-11ea-9ad9-1fa102fa0bdb.png)

As you can see, south of airport, airplanes entering the boundary will leave the boundary again. And because of this -200 points will be deducted for each airplane.

#### Steps to reproduce
- Just start KLAX and this will happen to all airplanes arrivals at south of airport

**Comment by Fechulo** [comment] 2020-05-19 12:29
@ghariman This is addressed in the airport guide and can be avoided by giving aircraft on those routes a direct to waypoint ZAPPP when they enter the airspace. This is caused by the lack of support for multiple airspace definitions, which will hopefully be fixed eventually. The airspace in that area does not go up all the way to FL190 in real life, as it does in the sim, so those aircraft would not actually enter the airspace at that point.

**Comment by erikquinn** [comment] 2020-05-22 02:06
If a particular real-world arrival sector would work these guys on the STAR, and own the airspace they go through, that's the airspace we should be showing as being owned by us. It is preferable to have innacurately _too much_ airspace over inaccurately _too little_ to get the job done. So I'd advocate for the better (interim) solution to be giving them the necessary airspace, though I agree that finishing #1307 is the proper resolution here.

**Comment by ghariman** [comment] 2020-05-23 03:27
Thank you! This will make it less burden to the ATC controller in this game.

**Comment by cake-pie** [comment] 2021-01-06 06:21
Fixed since #1307. GOATZ1 and DIRBY1 arrivals over Catalina Island no longer considered within airspace.

**Closed by cake-pie** 2021-01-06 06:21 UTC
Labels: airport work, refactor
