### ISSUE TITLE
Aircraft ignores 're-route' when issued with speed and altitude commands

### ISSUE THREAD

**Issue by JasonMKurtz** [openscope/openscope#151] opened 2017-01-21 23:34 UTC
When issuing "CALLSIGN sp 180 c 50 rr FIXA..FIXB", the speed and altitude are ignored (but are included in the read-back). 

When issuing "CALLSIGN rr FIXA..FIXB sp 180 c 50", all parts of the command are performed as expected (and everything is included in the read-back).

Related: #197.

**Comment by n8rzz** [comment] 2017-01-22 04:59
should be retested after [n8rzz#181](https://github.com/n8rzz/atc/issues/181) is merged

**Comment by erikquinn** [comment] 2017-02-06 01:42
This is caused by the fms generating fresh new `Leg`s and not remembering the altitude/speed assigned before it wiped the slate clean.

This issue is therefore a symptom of the core issue described in #197. Closing as duplicate.

**Closed by erikquinn** 2017-02-06 01:42 UTC
Labels: BUG
