### ISSUE TITLE
Route command denied by aircraft

### ISSUE THREAD

**Issue by Cheesydog** [openscope/openscope#974] opened 2018-05-25 00:01 UTC
Browser: Chrome 67.0.3396.57

Airport: All airports
 
Approximate play time before issue: 5 mins

#### Issue Description
_please include any console errors and/or screenshots_ 
Whenever using the route command, aircraft will respond with "routes do not have continuity"

#### Steps to reproduce
- 
Select aircraft or enter callsign
Attempt to use route command

**Comment by sam-irl** [comment] 2018-05-25 00:40
I'm not 100% sure about your situation, but I think this is a _feature, not a bug_, but this time actually a feature and not a bug.

The `route` command (I believe) only works if the assigned route is on a standard departure/arrival. Instead you should use the `reroute` command, separating noncontinuous waypoints with two dots (..).

I'll leave this open in case anyone else cares to chime in or correct me, but I'm labeling as invalid.

**Comment by Marcel510** [comment] 2018-05-25 00:57
Can you depict the situation you've noticed it? What exactly did you enter in the command line?

**Comment by erikquinn** [comment] 2018-05-25 02:02
It may be valid, but we will need way more information than is provided here. @cheesydog can you type out the full route an aircraft was on before rerouting them and the exact command you typed? That will help us figure it out.

**Comment by Cheesydog** [comment] 2018-05-25 14:00
Here is the command I use with a sample callsign:  ACA240 route yow.  And yes I have also tried this method and it failed: ACA240 route..yow,

**Comment by Marcel510** [comment] 2018-05-25 14:46
That's probably the problem, the entered routing has the include a waypoint that's in the current route of the aircraft. f.e. if the current route is 'AAAAA BBBBB CCCCC DDDDD EEEEE' and you issue '*Callsign* route XXXXX..YYYYY..CCCCC' the new route of the aircraft will be 'XXXXX YYYYY CCCCC DDDDD EEEEE'. If you just want to give a shortcut and not add any new waypoints use the proceed direct command ("pd" or "dct"). If you again take an aircraft with the route  'AAAAA BBBBB CCCCC DDDDD EEEEE' as an example and you issue '*Callsign pd CCCCC' the new route will be 'CCCCC DDDDD EEEEE'
Hope this helps

**Comment by sam-irl** [comment] 2018-05-26 00:37
@Cheesydog, more information on this can be found in the command reference either on the wiki or in the `documentation/` folder.

Closing as a pretty clear picnic

**Closed by sam-irl** 2018-05-26 00:37 UTC
Labels: invalid
