### ISSUE TITLE
Create handoff for departing aircraft

### ISSUE THREAD

**Issue by Hawaiicoder** [openscope/openscope#1828] opened 2021-06-09 21:49 UTC
Arrivals only contact us when they enter our airspace- we should implement something similar for departures, since they're not immediately in contact with departure- they stay with tower for a little while before they switch to the departure freq. Because of this, we should implement a feature similar to the arrivals.

**Comment by erikquinn** [comment] 2021-12-28 21:15
Duplicate of multiple more specific issues. closing.

**Closed by erikquinn** 2021-12-28 21:15 UTC
