### ISSUE TITLE
Airports with non-procedural arrival spawn patterns crash game

### ISSUE THREAD

**Issue by Wittner** [openscope/openscope#373] opened 2017-04-25 16:15 UTC
iMac 21.5-inch, Late 2015
macOS Sierra
Chrome 57...
Playing EIDW
When first arrival announces on screen, app freezes. Developer tools show (repeated over and over):

####
    AircraftStripView.js:387 Uncaught TypeError: Cannot read property 'toUpperCase' of null
    at AircraftStripView.value (AircraftStripView.js:387)
    at AircraftInstanceModel.value (AircraftInstanceModel.js:2023)
    at AircraftInstanceModel.value (AircraftInstanceModel.js:1879)
    at AircraftController.value (AircraftController.js:242)
    at App.value (App.js:392)
    at App.js:389
####

Here's the offending line for quick reference:
####
    switch (navMode) {
            case WAYPOINT_NAV_MODE.FIX:
                this.$heading.text(headingText);
                this.$destination.text(destinationText.toUpperCase());
    ...

**Comment by n8rzz** [comment] 2017-04-25 16:22
well 💩 , this looks like #370 all over again.

**Comment by erikquinn** [comment] 2017-04-25 16:22
![image](https://cloud.githubusercontent.com/assets/5103735/25396129/660a55e4-29b1-11e7-83c4-1fefefa5eb36.png)

@n8rzz Looks like it's a case of `destinationDisplay` being null because it was calculated by:
`destinationDisplay = this.fms.getProcedureAndExitName();` in `AircraftInstanceModel.updateStrip()`.

**Comment by n8rzz** [comment] 2017-04-25 16:23
yup 🤕. 

because we try to set that `destination` property using the `RouteModel` and blah blah blah.  I left a note in that linked issue about the root cause.

**Comment by n8rzz** [comment] 2017-04-25 16:23
I can't believe we never ran into this when we were testing it.  That's my bad, I should have run through some of these.

**Comment by n8rzz** [comment] 2017-04-25 20:52
this issue will be resolved by #370 

closing

**Closed by n8rzz** 2017-04-25 20:52 UTC
Labels: BUG

**Comment by Wittner** [comment] 2017-04-26 18:47
Cool. Thanks guys.

**Comment by erikquinn** [comment] 2017-04-26 18:58
And thank you for the report!

**Comment by erikquinn** [comment] 2017-04-29 10:57
Fixed via #376.
