### ISSUE TITLE
Taxing is too fast.

### ISSUE THREAD

**Issue by JamesZBL** [openscope/openscope#1392] opened 2019-06-01 03:17 UTC
After call taxi to xx runway, the aircraft suddenly appears  on that runway. That's too  fast.

**Comment by erikquinn** [comment] 2019-06-01 12:56
Hi @JamesZBL! Please see #1233 which already covers this.

Closing this issue as a duplicate of #1233.

**Closed by erikquinn** 2019-06-01 12:56 UTC
Labels: invalid
