### ISSUE TITLE
Feature request: toggle on/off visualization of STARs and Transitions

### ISSUE THREAD

**Issue by panther2** [openscope/openscope#318] opened 2017-04-14 15:54 UTC
So there is a button to toggle on/off the SIDs.
Have there ever been thoughts about enhancing this feature to show STARs and Transitions/Approaches?

That would be a huge help for the (non-professional) user. 
From my point of view I experience it to be quite easy to start all the planes and guide them to their exits. So seeing the SIDs is "nice to have". But I would profit a lot more from having an idea about the potential routes to the runways...
Of course I could read maybe the airport.json, evaluate some AIRAC data or use other software to see this visualized... but as the display of SIDs is already present, what about this additional feature (request)?

**Comment by headphase** [comment] 2017-04-14 16:38
I was thinking about this the other day; would definitely be a valuable addition to situational awareness.

Since the SIDS are blue dot lines; perhaps STARS can be yellow or red dots?


Over the long term it would also be great to have a submenu toggle for each individual STAR/SID so the user could select them according to their desire.

**Comment by Fechulo** [comment] 2017-04-14 16:45
This has already been discussed in #111

**Comment by erikquinn** [comment] 2017-04-14 17:00
😄 Definitely. And the plan is for red.

Closing as duplicate of #111.

**Closed by erikquinn** 2017-04-14 17:00 UTC
Labels: invalid
