### ISSUE TITLE
Remove Airport WIP Tags

### ISSUE THREAD

**Issue by Fechulo** [openscope/openscope#904] opened 2018-02-27 19:55 UTC
Since v6.0.0 broke every airport in the sim and adding them back would mean they must meet all the requirements, a WIP tag is no longer needed. This will also avoid bug reports in airports that are expected to be buggy.

**Comment by erikquinn** [comment] 2018-07-08 14:50
Accidentally recreated this as #1001. It has more details, so I will remove this one as the duplicate.

Closing as duplicate of #1001.

**Closed by erikquinn** 2018-07-08 14:50 UTC
Labels: refactor
