### ISSUE TITLE
RNAV/VOR/Visual Approaches

### ISSUE THREAD

**Issue by AviationFrank** [openscope/openscope#1947] opened 2022-04-17 23:29 UTC
It would be nice to be able to clear aircrafts for RNAV/VOR/Visual approaches, such as the famous Canarsie Approach into RWY13L/R of KJFK, the Visual Approach into RWY29 of KEWR, or the weird RNAV RNP into RWY19 of KDCA that is trying to maneuver around restricted airspace. There are a few more within the airports currently in OpenScope, such as the rare but fun visual approach into RWY1R of KSFO.

**Comment by cake-pie** [comment] 2022-12-14 16:39
Duplicate of #2; closing.

**Closed by cake-pie** 2022-12-14 16:39 UTC
