### ISSUE TITLE
Aircraft performs an orbit when swithcing the browser tab

### ISSUE THREAD

**Issue by georgeenciu** [openscope/openscope#482] opened 2017-05-22 13:45 UTC
Found this weird behavior when I switch from the game tab to another tab:

`LOT815` is following `TOSVI2U` arrival which goes; `TOSVI`, `UVALU` then `OP088`, he is currently heading to `UVALU`

![image](https://cloud.githubusercontent.com/assets/1264087/26311405/db99e37c-3f0c-11e7-95a6-d351fd533310.png)

I clicked on another tab in the browser and stood there as long as it took the plane to pass `UVALU` then I switch to the game again to find the plane still heading to `UVALU`(see the strip) even if the plane passed the fix, so it makes a left orbit to `UVALU` and continues to `OP088`

![image](https://cloud.githubusercontent.com/assets/1264087/26311570/728ee14c-3f0d-11e7-944d-f936c613d3a5.png)

**Comment by n8rzz** [comment] 2017-05-22 13:58
this seems related to #296.  If I remember correctly, there was a change in how calculations are handled (or not handled) when the game loop is paused that could be leading to this.  Basically, even though the app is paused, my hunch is, the physics calculations are continuing.  Thus, when the app is unpaused, everything jumps ahead as if things were never paused in the first place. 😦

**Comment by georgeenciu** [comment] 2017-05-22 14:44
this does not happen if I just pause the game by the button

**Comment by erikquinn** [comment] 2017-05-22 14:56
Yep, definitely a symptom of #296. The clock keeps running but the positions are not recalculated. When you click back in, the physics resume and say "it's been 247 seconds since the last position update, multiplied by the speed... You have moved 36.14 miles in the current direction!" Obviously they then end up too far past the fix to be considered "over" it (which is what triggers the turn to the next fix).

**Comment by erikquinn** [comment] 2017-05-22 14:56
Closing as duplicate of #296.

**Closed by erikquinn** 2017-05-22 14:56 UTC
Labels: invalid
