### ISSUE TITLE
Climb/Descend Rates on Certain Aircraft

### ISSUE THREAD

**Issue by f18bkr** [openscope/openscope#876] opened 2018-02-06 11:25 UTC
Browser: Chrome

Airport:  Varies

Approximate play time before issue: Varies

Hi all, first time in this area and I'm hoping this is the right place to report an issue. Firstly, i wanted to thank you for providing and maintaining a quality sim here. As a shift worker behind a console, this game keep me awake and focused on those graveyard shifts. 

One thing I've noticed on the MD80/82/83/88/90, B717, CRJ2/7/9, and a few other T-tailed GA jets is that the climb and descend rates are far too slow. I often find other a/c overtaking the above a/c some 20-30nm out from the airport because they aren't above 10k feet just yet. I feel these rates should be similar to the B737/A320 rates.

Hope I'm not in the wrong here and that this is the right place to report.

Thanks!

**Comment by n8rzz** [comment] 2018-02-06 12:35
Thanks for the report, this is absolutely the right place to report an issue!

We have taken great care in making things as real as possible as it relates to aircraft performance and airport procedures.  But, sometimes, things aren't quite right.  The good news is that this is an open source project so, if you see something that isn't quite right, you have the power to fix it!  

Each aircraft has an `AircraftTypeDefinition` file located in the `assets/aircraft` directory.  As an example, the aircraft file for the MD82 is located here: https://github.com/openscope/openscope/blob/develop/assets/aircraft/md82.json

Feel free to take a look through those and see if some of the numbers are inaccurate.

You can also join us on slack but registering at http://slack.openscope.co

**Comment by f18bkr** [comment] 2018-02-07 01:44
Just looking at different aircraft files, this is what I found amount narrowbodies and commuter a/c.

B737 Family- 3000fpm↗ and 3000fpm↘

A32X Family- 3500fpm↗ and 3000fpm↘

MD8X/B712 Family- 1215-1300fpm↗ and 1430-1500fpm↘

E135/145/E50P/E545/E55P- 1500fpm↗ and 1500fpm↘

CRJX Family- 2000fpm↗ and 1670fpm↘

The heavy aircraft typically have a fpm↗ ~2000-2500 so the MD8X/717, ERJs and CRJ could definitely us an adjustment to ~3000fpm up and down.

Hope this helps.

Thanks

**Comment by PFunk49** [comment] 2018-02-23 02:42
I have no idea why the T tails would be given such terrible descent rates. The DC9 family has always been known for being easy to slow down. It can deploy flaps at ridiculously high speeds unlike the Boeing for instance, which the 738 has been notorious for being hard to slow down. Older airplanes should be easy to descend fast owing to their less aerodynamic qualities. I also think I read the CRJ is a pig on climbout and shouldn't be matching a B738 or A320. MD80 shouldn't be a bad climber either.

**Comment by indianbhaji** [comment] 2018-06-09 21:32
Duplicate of #961 and resolved

**Closed by indianbhaji** 2018-06-09 21:32 UTC
Labels: NEEDS INVESTIGATION
