### ISSUE TITLE
Strange problems at KPHX

### ISSUE THREAD

**Issue by ron-eo** [openscope/openscope#378] opened 2017-04-25 21:47 UTC
Wow! So many problems...

1. when departing, some planes go into a HOLD circle right above the airport and typing any kind of turn, route or RR command when in this state is ignored
2. setting SP 0 actually sets speed to 0...I haven't seen if it actually goes to 0 but the slowest speed possible for the plane is a guess now
3. the flight strip on the right shows inaccurate altitudes and speeds for incoming aircraft
4. some planes incoming, once they pass their first waypoint, speed up to 320 knts from 250 but then go back down at the next waypoint

Was there a recent update for this airport or the openscope.co site overall? I haven't checked any other airports yet as this one is a favourite.

**Comment by Fechulo** [comment] 2017-04-25 21:55
@ron-eo I can't seem to recreate the holding aircraft on departure, could you maybe send a picture and some more information about this?

Indeed v5.0.0 was released recently but no changes were made to KPHX in particular,

**Comment by ron-eo** [comment] 2017-04-26 00:36
So now, it was working ok but still weird speeds relative to the strips and the rr command does not function for me. 

As well, as the first pics show (capture1 and 2), one second everything was fine but then the next second, it was like I was looking at someone else's simulation!

Now, it gets to a point and just freezes! I cleared my cache and even rebooted my Surface Pro 4 but the problems persist. I tried it with IE 11.0.40 and with Firefox 45.8.0 but the same results.

My latest game is still frozen.

![capture1](https://cloud.githubusercontent.com/assets/25729938/25412682/96b72398-29f2-11e7-92be-9ba433961bc9.JPG)
![capture2](https://cloud.githubusercontent.com/assets/25729938/25412689/99e23a9e-29f2-11e7-8a3c-013581070670.JPG)

**Comment by ron-eo** [comment] 2017-04-26 00:39
Here is a screen shot of my frozen screen...
![capture5](https://cloud.githubusercontent.com/assets/25729938/25413285/43b76298-29f7-11e7-88f5-0a9f911f88bc.JPG)

**Comment by n8rzz** [comment] 2017-04-26 01:35
Does the sim freeze as a result of a command?  And when it does, are there any errors in the devtools console?

For the speeds, are you talking about the info box displayed next to each aircraft.  Or the strips on the side?  The speeds listed on the strips are more often _target_ speeds and not actual. Same with the altitude.

For the `rr` command, refer to [the wiki](https://github.com/openscope/openscope/wiki/Command-Reference) and verify you are passing the arguments correctly. This _shouldn't_ be broken and hasn't changed since I rewrote the command parser, but it's possible.  So I want to rule out the basics first.

**Comment by ron-eo** [comment] 2017-04-26 03:23
Good catch, n8rzz! Yes, when I type a "rr" command, everything stops. As per the screen shot, it indicates the reroute is accepted but the sim freezes.
![capture6](https://cloud.githubusercontent.com/assets/25729938/25416847/2044ad5e-2a0e-11e7-8a25-caadd701a7c6.JPG)

**Comment by n8rzz** [comment] 2017-04-26 03:25
What is the exact command you are issuing so I can try and reproduce it.

**Comment by n8rzz** [comment] 2017-04-26 03:29
What happens if you do it with two fixes?

Something like: `rr keeps..hikid`

**Comment by n8rzz** [comment] 2017-04-26 03:38
looks like this is probably related to #370

**Comment by ron-eo** [comment] 2017-04-26 13:17
It does the same...registers on the screen the full address but freezes as well.

Oh, just to show I'm not hallucinating, here is a screen shot of the loop above the airport. I start it on runway 8 but when it initially appears closer to 7L and the front is pointing north. Maybe is it a helicopter? LOL! 

As well, the inbound bottom right shows 32 as it's speed bur when first coming in it was 25.

![capture7](https://cloud.githubusercontent.com/assets/25729938/25436360/16d9ccc4-2a61-11e7-95fd-68cff0b8320e.JPG)

**Comment by ron-eo** [comment] 2017-04-26 13:29
I have been monitoring it and, although the screen is stuck, the sim is continuing as the strip is constantly updating as new inbounds come in and the 3 I did depart leave the area!

**Comment by n8rzz** [comment] 2017-04-26 15:01
what kind of console errors are you seeing when it hangs like that?  `ctrl + shift + i` on chrome to open dev tools and then click on the console tab.

**Comment by ron-eo** [comment] 2017-04-26 21:11
Here is a snip of  the dev console on IE...streaming errors when I do the rr command!
![capture8](https://cloud.githubusercontent.com/assets/25729938/25457197/69b1dea4-2aa3-11e7-9baa-7761458084b3.JPG)

**Comment by ron-eo** [comment] 2017-04-26 21:25
I just had another departing flight do the loop thing and a similar stream of errors came out...screen is frozen again.
![capture10](https://cloud.githubusercontent.com/assets/25729938/25457744/4b912c20-2aa5-11e7-8bb0-8c4d73501955.JPG)

**Comment by n8rzz** [comment] 2017-04-26 22:43
I was about to say this should be solved with #370, but looking at it on that branch that doesn't seem to be the case.  I have identified where this problem is coming from, though, so thank you for the screenshots.  Those gave me the clue I needed.

If you'd like to check on progress, take a look at https://openscope-dev-pr-376.herokuapp.com/

Keep in mind that this issue is still present on that link, for now. 😉

**Comment by ron-eo** [comment] 2017-04-26 22:49
OK, thanx, n8rzz! I love this sim so I'm glad I can help out!

**Comment by n8rzz** [comment] 2017-04-26 22:53
your help is appreciated!  we don't like bugs, but we do like bug reports.  if we know about it, we can fix it!

Also, I'll be pushing a fix for the `rr` bug to the url I posted above in the next 5mins.

**Comment by ron-eo** [comment] 2017-04-27 12:07
OK, I've been using it on Firefox and avoiding the rr as turns are working. I have one that has spiraled way above the airport but it is out of range 21000 I believe. Will it run out of gas? LOL! Here is a screen shot of that. And planes seem to be much more responsive...I think the game runs close to real time now...less delay.
![capture11](https://cloud.githubusercontent.com/assets/25729938/25482596/859ce410-2b20-11e7-9565-d4173430e492.JPG)

**Comment by erikquinn** [comment] 2017-04-29 10:58
Closed via #376.

**Closed by erikquinn** 2017-04-29 10:58 UTC
Labels: BUG
