### ISSUE TITLE
Tab not switching to Scope Commands v6.29.0 beta

### ISSUE THREAD

**Issue by wmstapp** [openscope/openscope#1982] opened 2022-07-29 16:57 UTC
Browser: Chrome

Airport: checked 3 different ones KSLC, KELP, KDCA

Approximate play time before issue: Immediate

#### Issue Description
_please include any console errors and/or screenshots_ 
[Tab] key produces a "search commands" menu instead of switching to Scope Commands mode.

#### Steps to reproduce
- Load an airport. Press [Tab]
![OpenScope Err](https://user-images.githubusercontent.com/45436083/181807918-f05b83af-b769-419b-a65e-a6c651c88fb1.PNG)

**Comment by cake-pie** [comment] 2022-12-03 09:37
Working as intended. Some keys have been reassigned as of 6.28.0; the ` Tab ` key is used for the new search/autocomplete, and instead the backquote `` ` `` key just above is used for switching between Aircraft Commands and Scope Commands (see [commands documentation](https://github.com/openscope/openscope/blob/2860a23834ec11311cea47bac199031d0844955b/documentation/commands.md)).

**Closed by cake-pie** 2022-12-03 09:37 UTC
