### ISSUE TITLE
2nm range rings? 

### ISSUE THREAD

**Issue by Fltchk31** [openscope/openscope#1170] opened 2018-11-05 02:19 UTC
Browser:safari

Airport:all

Approximate play time before issue:0

#### Issue Description
_please include any console errors and/or screenshots_ 
Enhancement suggestion. Would it be possible to have 2nm range rings in addition to the current 5nm range rings?  Would reflect better scope flexibility in real world. 

#### Steps to reproduce
-

**Comment by Marcel510** [comment] 2018-11-05 12:41
For which situation exactly would you need 2nm rings?

**Comment by felixscheffer** [comment] 2018-11-05 12:42
duplicate of #1032

**Closed by felixscheffer** 2018-11-05 12:42 UTC
Labels: enhancement
