### ISSUE TITLE
UI inconsistencies / UX issue due to window onblur / onfocus

### ISSUE THREAD

**Issue by cake-pie** [openscope/openscope#1335] opened 2019-03-05 07:45 UTC
Also see #1148.

Browser: chrome (any)

Airport: any

Approximate play time before issue: n/a

#### Issue Description
Control button UI elements become inconsistent due to window onblur / onfocus.

**Timewarp**: if timewarp (x2 / x5) is active when app loses focus, `_onWindowBlur` [resets timewarp to x1](https://github.com/openscope/openscope/blob/3763f6e966350690699bea6f00a21147c0e3490b/src/assets/scripts/client/game/GameController.js#L569-L571) without updating the button visuals to match.

**Pause**: even if app was already (manually) paused when loses focus, `_onWindowFocus` [unpauses it](https://github.com/openscope/openscope/blob/3763f6e966350690699bea6f00a21147c0e3490b/src/assets/scripts/client/game/GameController.js#L584) without updating the button visuals to match.  

Furthermore this behavior is not ideal; if the simulation was manually paused, it would be preferable that the app respect the paused state and not unpause automatically.

#### Steps to reproduce

**Timewarp**
* turn on timewarp by clicking button, note button color change indicating timewarp active
* tab out and then back in
* timewarp is now inactive, but button has not been updated

**Pause**
* pause by clicking button, note button color change indicating paused state
* tab out and then back in
* unpaused but button has not been updated

**Comment by felixscheffer** [comment] 2019-03-05 10:59
duplicate of #1148

**Comment by cake-pie** [comment] 2019-03-05 13:47
Ah, my bad.

**Comment by erikquinn** [comment] 2019-03-05 14:41
Linked in #1148, closing as duplicate.

**Comment by erikquinn** [comment] 2019-03-05 14:41
Actually, this already has the PR, so we'll do the reverse.

**Closed** 2019-03-06 17:42 UTC
Labels: BUGFIX, has pull request
