### ISSUE TITLE
Issues with EIDW Under v5.2.1

### ISSUE THREAD

**Issue by scott-j-smith** [openscope/openscope#554] opened 2017-07-05 01:29 UTC
Hi folks,

Congrats on releasing v5.2.1.  I'm still getting used to the new look & feel of the flight strips.  I was playing EIDW (one of the 3 airports not in WIP), and I ran into a couple of issues.

1.  The departure exit point / arrival entry point names in bold cyan text are overlapping and impossible to read (see screen shot 1).  

2.  On departure procedures BAMLI and  NEVRI(AB) the departing aircraft do not clear FL40 before crossing into the restricted area to the north of the airfield, leading to a -200 point penalty.  Is that correct?  I'd expect the procedures to be designed to prevent issues, because of this statement on the Wiki command reference page under the "CVS" command:  _They will climb to their filed cruise altitude, whilst complying with all altitude and speed restrictions posted in the procedure_.    Example:  Flights STK383 and STK935

3. Departing aircraft penalized for leaving the control area without clearance (-25 point penalty).  Is this a new feature that controllers need to be aware of?  Are the changes documented somewhere?  I'm not seeing any new commands in the Wiki page, just one deleted (Fix).   I assumed that once the flight was issued the "CAF" command, and then the "CVS" en route it would proceed on its merry way.  Example:  Flight N749NX (after running a few minutes past the point of the screen shot 1 below)

4. Arriving aircraft given the command to "DVS" get an assigned altitude of 0 in the flight strip (see screen shot 2).  Is this by design?  (Although I did find by accident, because I wasn't paying attention to all the planes and missed some arrivals, that they will follow the arrival procedure on their own without that command anyway.)  Example:  Flight BCY858

Thanks,
Scott

Screen Shot 1:
![image](https://user-images.githubusercontent.com/22403776/27845213-e546445a-60fa-11e7-8758-befce24f275b.png)

Screen Shot 2:
![image](https://user-images.githubusercontent.com/22403776/27845924-48f55b52-6101-11e7-8f71-22460f233d67.png)

**Comment by Fechulo** [comment] 2017-07-05 01:59
1.  I believe this has to do with the suffixes, which are now actually in use, but I guess they're all being drawn on top of each other because they're all defined as 1 procedure in the airport file.

2. The procedures don't have any altitude restrictions to avoid EID1. The issue is that EID1 is a danger area activated by NOTAM, so it's not normally active (In fact, I just noticed it should go up to 40,000ft not 4,000ft). This area should probably be removed to prevent problems like these. This might apply to some other areas at EIDW.

3. I believe this is an issue that's being worked on? @n8rzz could confirm. The problem is that some of the SID's end inside the airspace. When the aircraft reach the final fix and continue on their heading, so when they leave the airspace, they aren't flying to a fix, causing a penalty.

4. Arriving aircraft descend via the STAR by default, so there's no need to give them the 'dvs' command. However, the assigned altitude shouldn't be 0, so that's something to look into.

**Comment by n8rzz** [comment] 2017-07-05 02:49
To point #3, its actually the other way around. Some procedures end _outside_ of controlled airspace and were incurring a penalty.  This case was fixed in this latest release.  The way @Fechulo describes it, though, could also be a problem.  🤔 

If so, that deserves it's own issue.

**Comment by scott-j-smith** [comment] 2017-07-06 01:52
Hi guys,

Found another bug.  Was playing same airport again today, and sometimes I see a flight seem to land way past the runway, and sometimes well before it, but no errors posted in the game.  Example:  BCY289 (screen shot below).  In the pic it is landing just to the left of the the "10" runway number label near the center of the screen, which is well past the end of RWY 28.  Could be a graphic display / refresh issue?   Is this a known issue?   I'm using Google Chrome with the latest updates.

Scott

![image](https://user-images.githubusercontent.com/22403776/27892135-edb89db4-61cb-11e7-8034-838772c0e1bd.png)

**Comment by n8rzz** [comment] 2017-07-06 15:55
well that is not as designed. ☹️ 

@scott-j-smith when you have a minute, could you split up each of the issues you've called out here into new issues? One per item except for the one @Fechulo tackled yesterday.  

Thanks!

**Comment by scott-j-smith** [comment] 2017-07-06 17:35
OK, Nate, I will do that as soon as I can.

**Comment by scott-j-smith** [comment] 2017-07-15 02:11
Per Nate's request, am opening the following cases to track individual issues:

Issue 1 above now in case #565

Issue 2 above already being tackled by @Fechulo  in Bugfix/554 #561 if I read the notes correctly, and _will remain in this case as the primary issue_.

Issue 3 above now in case #566

Issue 4 above now in case #567

Issue 5 (not numbered, added Jul 5, now in case #568

**Comment by erikquinn** [comment] 2017-07-15 18:02
@scott-j-smith thanks for splitting these up so it's one issue per problem. Makes it a lot easier to work through on our end. :+1: 

Since all these are now covered in their own individual issues, closing this as a duplicate.

**Closed by erikquinn** 2017-07-15 18:02 UTC
Labels: CONTAINS MULTIPLE ISSUES

**Comment by n8rzz** [comment] 2017-07-15 18:22
@scott-j-smith I second that. Thank you very much!
