### ISSUE TITLE
Arrivals descending below STAR entry altitude restrictions

### ISSUE THREAD

**Issue by ij1** [openscope/openscope#464] opened 2017-05-15 21:12 UTC
I noticed while testing EFHK that arrival routes produce descend+climb before entering STAR part of the route.

E.g., route "ENETI..AMROT..LAKUT.LAKUT.EFHK" that spawn aircrafts at FL190 has time to descend to ~FL80 before reaching AMROT. They would go all the way to 3000ft (matching to the final altitude at the end of STAR) if there would be enough time before reaching the last fix before the entrypoint of STAR. After passing AMROT, the aircrafts climb back to FL100 (LAKUT is defined as ["LAKUT", "A100+"]) if there is enough time or busts the restriction otherwise.

**Comment by erikquinn** [comment] 2017-05-15 21:44
This is a symptom of a deeper problem: the fact that the vertical navigation logic used to guide aircraft through altitude restrictions are only ever looking at the restriction of the current waypoint. So if we have to descend by 10,000 feet between A and C (50 miles), it's easily doable. But if we stick point B in the middle with no restriction, the aircraft will go all the way to B without realizing they should have started their descent to arrive to C at the correct altitude.

It'll be sorted out soon, for now you can just ignore the behavior. And though it may be tempting, please do not create a workaround to this bug by adding a "fake" restriction of 10,000 feet at AMROT. We always want to stick to listing the procedures exactly as published. Then when we fix the bug, all should be working perfectly. :smiley:

**Comment by erikquinn** [comment] 2017-05-15 23:41
Closing as duplicate of #32.

**Closed by erikquinn** 2017-05-15 23:41 UTC
Labels: invalid
