### ISSUE TITLE
DVS causing aircraft to be at altitude 000 while airborne

### ISSUE THREAD

**Issue by Van-atVT** [openscope/openscope#629] opened 2017-08-14 04:27 UTC
Browser:
Chrome (latest version)
Airport:
KBOS
Approximate play time before issue:
5-10 mins
#### Issue Description
_please include any console errors and/or screenshots_ 

1. - when you re-apply DVS (@felucho states that STAR is applied by default) it not only assigns the altitude to zero (#566) but the aircraft don't follow the 1000ft altitude fail-safe and hit zero. (image 1)
![screenshot 5](https://user-images.githubusercontent.com/30939758/29257822-f9caa5ae-8082-11e7-86a9-d8c8239f701f.png)

2. - with a little more investigation, once it reaches zero it reports as NaN (image 2)
![screenshot 8 _li](https://user-images.githubusercontent.com/30939758/29258193-901f4882-8085-11e7-9954-172759867d93.jpg)

3. - Also, an aircraft is allowed to reach an alt of zero without being considered crashed???? 

#### Steps to reproduce
- use the DVS command on an arrival
- have it fly ILS to a runway

**Comment by erikquinn** [comment] 2017-08-14 11:17
Hi @Van-atVT!

Thanks for the very detailed report here. We do already have this issue logged, and I have updated that issue (#567) with your excellent screenshots as well as some of your thoughts.

Closing this as duplicate of #567 to keep things orderly. :smile: 

Thanks again!

**Closed by erikquinn** 2017-08-14 11:17 UTC
