### ISSUE TITLE
Change styling of non-option text in settings menu

### ISSUE THREAD

**Issue by sam-irl** [openscope/openscope#1303] opened 2019-01-29 04:25 UTC
_from @n8rzz in #1302_:
I'm happy with how this is written and how it works.  I think, though, that we can do some small tweaks to the styles:

Currently this looks like:
<img width="595" alt="screen shot 2019-01-28 at 8 07 36 pm" src="https://user-images.githubusercontent.com/3325985/51879277-6881f980-2338-11e9-9458-36f76ea4beee.png">

Since this is an effective subtitle, or aside of some sort, I feel we should de-emphasize the text a little bit so it is differentiated from the other options.  Maybe something like:
<img width="761" alt="screen shot 2019-01-28 at 8 04 51 pm" src="https://user-images.githubusercontent.com/3325985/51879265-5607c000-2338-11e9-9e15-b2fc24d67b8d.png">

**Comment by erikquinn** [comment] 2019-01-29 15:27
Duplicate of #1272. Will be handled in #1302 (feature/1272). Closing.

**Closed by erikquinn** 2019-01-29 15:27 UTC
Labels: invalid
