### ISSUE TITLE
EIDW - Leaving Controlled Airspace without proper clearance

### ISSUE THREAD

**Issue by matt5611** [openscope/openscope#575] opened 2017-07-16 01:14 UTC
As title suggests, departing aircraft leaving controlled airspace without clearance.

E.G. departing via OLONO on published SID Ray 28... issued via CAF & CVS commands. No further instructions given after Taxi and Take-off... When aircraft arrives at OLONO the player is penalised for incorrectly leaving controlled airspace.

Note: this is NOT limited only to OLONO but the vast majority of outbound points.

Departing aircraft to the north, will exit, and then proceed to turn to heading ~160 and re-enter... the subsequent re-exit causing penalisation to player.

Aircraft arriving from the North East will KOGAX... after which some seem to have an issue with the left turn to the next point (fly-over) and will exit controlled airspace on their STAR, re-enter no more than 10 seconds later as the turn back to the SW for the next STAR tracking point.

All arriving aircraft left on STAR's tracking to the waypoints near DW814 (east of aerodrome), caused as aircraft miss the fly-over waypoint or take longer than anticipated to turn, interrupting their tracking to the subsequent waypoints, causes exit of controlled airspace, again the player is penalised.

In normal playing, it is not unusual to receive -1000 points in 15 minutes purely by departing aircraft on SID's, and leaving aircraft to fly STAR's (with vertical separation), purely because of aircraft leaving CTA.

**Comment by erikquinn** [comment] 2017-07-16 01:36
Hello @matt5611!

Yep, this is caused by the aircraft's route ending before they exit the airspace. It is actually already logged in issue #566, and will be fixed hopefully this sprint (so you should be able to see the change happen when we push the new version to the site, which is the 1st of every month).

Appreciate the issue, and particularly the thorough descriptions! I've left a reference to this issue in the previously existing one. If you notice anything else not working right, drop us another issue, and as always, feel free to message any of us directly, or through the `#bugs` channel of our slack team, and we can troubleshoot live, or share this sort of info with you. You can join the slack team here if you like: [http://slack.openscope.co](http://slack.openscope.co).

Closing as duplicate of #566.

**Closed by erikquinn** 2017-07-16 01:36 UTC
Labels: invalid
