### ISSUE TITLE
how to stop missed approach

### ISSUE THREAD

**Issue by victory1729** [openscope/openscope#1401] opened 2019-06-21 17:41 UTC
Browser: Chrome

Airport: Dubai

Approximate play time before issue: 5-10 min

#### Issue Description
_please include any console errors and/or screenshots_ 

The issue is that when a takeoff is happening a plane is also about to land. Every single time I see a message missed approach.

I just wanted to know how much separation is required and how will I be able to know that while playing

#### Steps to reproduce
-

**Comment by erikquinn** [comment] 2019-07-19 02:01
Hey @victory1729! If they are going around with a red message, it is most likely because they are intercepting the localizer ABOVE the glideslope. Get them to a lower altitude, and have them intercept the localizer further out from the airport. There's also a small chance that aircraft who descend poorly (especially E135/E55P/etc) are unable to make the descent if they're at too fast an airspeed, so you may even consider telling everyone to reduce to 210 knots (or less) to be sure that isn't a contributing factor.

It's also worth mentioning we are having some issues at the moment with aircraft climbing themselves while on short final. We are investigating the cause of this. You can see further information in #1395. The poor-descending-aircraft issue number is #1398. 

Given those existing issues, I am going to close this issue as being caused by one of those. Feel free to monitor those linked issues, as they are the ones we'll use to track the work being done on getting them fixed. Thanks!

Closing as duplicate of #1395.

**Closed by erikquinn** 2019-07-19 02:01 UTC
Labels: invalid
