### ISSUE TITLE
Support for complex route clearances

### ISSUE THREAD

**Issue by owendelong** [openscope/openscope#914] opened 2018-03-02 20:22 UTC
Browser: Any

Airport: Any

Approximate play time before issue: N/A

#### Issue Description
FEATURE REQUEST

It would be nice to be able to assign aircraft a route clearance involving more than one fix.

It would also be nice to be able to use crossing altitudes in those clearances.

For example, an aircraft off KSFO climbing through 2000 headed to ALTAM with a clearance of ECA ALTAM might conflict with an arrival from the East descending through 9000 on its way to 4000 . In order to avoid this, it might be convenient to  divert the climbing aircraft north and vector it on course once it's high enough to clear the conflicting traffic.

A clearance such as route OSI STINS@9000+ ECA AF (read "Cleared Woodside STINS Manteca then as filed, cross STINS at or above 9000") would do the trick. (There are probably better routes, but these are real world fixes I can recall from memory and they illustrate the desired behavior.

#### Steps to reproduce
Feature request, not a bug report

**Comment by Marcel510** [comment] 2018-03-02 21:26
Crossing restrictions should also be added to the normal climb/descend command e.g. `c 120@AMEXO` `climb 12000 to be leveled at AMEXO` (see also in #10).

**Comment by erikquinn** [comment] 2018-03-04 20:29
> It would be nice to be able to assign aircraft a route clearance involving more than one fix.

This is able to be done now, eg `route fixxa..fixxb..fixxc.prcdr1.fixxd..fixxe..fixxf`, etc. See the [aircraft command reference](https://github.com/openscope/openscope/blob/develop/documentation/aircraft-commands.md#routing-commands) for further on that.

> It would also be nice to be able to use crossing altitudes in those clearances.

Agreed. Documented feature planned in #10. 👍 

> For example, an aircraft off KSFO climbing through 2000 headed to ALTAM with a clearance of ECA ALTAM might conflict with an arrival from the East descending through 9000 on its way to 4000 . In order to avoid this, it might be convenient to divert the climbing aircraft north and vector it on course once it's high enough to clear the conflicting traffic.
>
> A clearance such as route OSI STINS@9000+ ECA AF (read "Cleared Woodside STINS Manteca then as filed, cross STINS at or above 9000") would do the trick. (There are probably better routes, but these are real world fixes I can recall from memory and they illustrate the desired behavior.

For example, this could be done as `callsign route osi..stins..eca`, and it will automatically rejoin the remainder of the flightplan after ECA.

---

Closing as duplicate of #10.

**Closed by erikquinn** 2018-03-04 20:29 UTC
Labels: invalid
