### ISSUE TITLE
Add ability to define approaches/transitions

### ISSUE THREAD

**Issue by willfrd** [openscope/openscope#987] opened 2018-06-02 20:37 UTC
It would be very handful if just as SID's and STAR's are defined in there individual places, to be able to define `"transitions": {....}` also called approaches in Europe `"approach": {....}`, with all the available approaches/transitions for the airfield, this would have to go together with the posibility to define in each STAR, the appoaches/transitions available from it, so openscope can join star with approach/transitions, to make a plane succesfully land :grin:

*Directed towards all the coders of this sim., particularly the miraculous progamming hands of @nategeslin :wink:*

**Comment by erikquinn** [comment] 2018-06-02 20:50
That's exactly the plan 😄: `transitions: { . . . }` and `approaches: { . . . }`. Then we can support full "transition procedures" like used in europe, with their own identifiers included in the flight plan route string, while also supporting US-style `SQS UJM3 KMEM` being `Sidon transition, Marvell 3 arrival` and `GLH UJM3 KMEM` being `Greenville transition, Marvell 3 arrival` as _exit_ or _entry_ points within the appropriate SID/STAR procedure. In theory, multiple entries/exits combinations could be used _in addition_ to the combinations possible between SID/STAR procedures and transition procedures and approach procedures. Though I have yet to meet a person who would be able to keep track of anything at that point. lol

> all the available approaches/transitions for the airfield, this would have to go together with the posibility to define in each STAR, the appoaches/transitions available from it, so openscope can join star with approach/transitions, to make a plane succesfully land

In a way, this is already natively possible. If certain fixes are included in the runway section of a SID/STAR, aircraft will follow those fixes. We can tell the aircraft to expect a new arrival runway using the `expect` (`e`) command with the runway. This will cause their FMS to adjust and fly the appropriate route for that runway. So in theory, to your example, we would be able to plug in the approaches into the `rwy` sections, have them filed along the STAR when they enter our airspace and then tell them `e 28r` and they will fly that chain of fixes. Not realistic, because we would be clearing them explicitly for the approach, and/or to fly the transition procedure (as appropriate).

This is actually a very long-standing issue (about as old as it gets), and is already documented. So though I appreciate the effort to write it up, I will have to close as a duplicate of the other issues for the same thing. 😉 

Closing as duplicate of #2 and #3.

**Closed by erikquinn** 2018-06-02 20:50 UTC
