### ISSUE TITLE
Add Visual/RNAV/LDA approaches

### ISSUE THREAD

**Issue by JPmAn24** [openscope/openscope#1009] opened 2018-06-26 03:00 UTC
This is a thing I've seen in real life, and would add a lot to the game. The only supported approach is ILS.
There would be a few new types of approaches, such as:

- Visual
  - Approach that uses visual navigation
  - Example: RIVER visual into RWY19 at DCA https://flightaware.com/resources/airport/KDCA/IAP/RIVER+VISUAL+RWY+19

- RNAV
  - Approach that uses RNAV waypoints
  - Example: RNAV PRM X 28L at SFO 
https://flightaware.com/resources/airport/KSFO/IAP/RNAV+(GPS)+PRM+X+RWY+28R

- LDA
  - Approach using Localizer only. Used with approaches that have to avoid terrain or restricted areas
  - Example: LDA X RWY8 at PAJN
https://flightaware.com/resources/airport/PAJN/IAP/LDA+X+RWY+08

**Comment by indianbhaji** [comment] 2018-06-26 12:20
This appears to be a duplicate of #2 and #3, I'll close this but reopen this issue if it really isn't a duplicate

**Closed by indianbhaji** 2018-06-26 12:20 UTC

**Comment by erikquinn** [comment] 2018-06-26 15:53
I love the idea as well. #2 has been extended to explicitly include LDA and charted visual approaches. #3 doesn't apply (has to do with straight up "see the airport"/"yep"/"fly at it"/"roger" situations).

Since this issue is covered by others in its entirety, it is correctly closed. :+1:
