### ISSUE TITLE
rr command does not work for aircraft still on ground

### ISSUE THREAD

**Issue by edge33** [openscope/openscope#470] opened 2017-05-19 10:28 UTC
`uncaught TypeError: Cannot read property 'toUpperCase' of null
    at AircraftStripView.value (bundle.min.js:17)
    at AircraftInstanceModel.value (bundle.min.js:17)
    at AircraftCommander.value (bundle.min.js:15)
    at InputController.value (bundle.min.js:14)
    at InputController.value (bundle.min.js:14)
    at InputController.value (bundle.min.js:14)
    at HTMLInputElement.<anonymous> (bundle.min.js:14)
    at HTMLInputElement.dispatch (bundle.min.js:8)
    at HTMLInputElement.elemData.handle (bundle.min.js:8)`

when issuing 

`rr [waypoint]`

**Comment by n8rzz** [comment] 2017-05-19 11:11
@edge33 Well that's not good. I have a few more questions for you:

- what airport is this at
- was this an arrival or departure
- is this happening every time you run the rr command, or just to specific fix?

**Comment by n8rzz** [comment] 2017-05-19 11:12
Likely resolved by #285

**Comment by edge33** [comment] 2017-05-19 12:49
It seems to happen every time I assign a fix when the aircraft is still on the ground

**Comment by n8rzz** [comment] 2017-05-20 20:06
@edge33 it seems you identified a hole in some of our defenses 😉 

The `rr` command is not designed to be used while on the ground.  Typically, one would issue a new SID for a departing aircraft.  Or, wait till an aircraft has taken off before re-routing them.

There is, however,  a bug here.  There should be a warning displayed stating that `rr` is not valid for aircraft on the ground and the command should not be executed.

**Comment by n8rzz** [comment] 2017-05-20 20:09
- [ ] add check for current aircraft state (there may be an `.isOnGround()` method or something similar that already exists
- [ ] warning should be displayed when an aircraft is on the ground
- [ ] additional tests should be added for this specific edge case

**Comment by erikquinn** [comment] 2017-05-20 20:37
There is a _significant_ use case for reroutes on the ground. We'll have to figure out a way to support it. I'm not sure how I overlooked that it wasn't working, to be honest. :confused:

**Comment by n8rzz** [comment] 2017-05-20 20:48
seems I was incorrect.  Erik is the authority here but, nonetheless, seems we have a 🐛

**Comment by cake-pie** [comment] 2021-01-19 19:10
Unable to reproduce on 6.22. Issued `rr` with both individual waypoint as well as more complex routing as the first command given to multiple departure aircraft at EDDM and KBOS and encountered no problems. Aircraft flew the reassigned routing when subsequently issued appropriate commands e.g. `caf cvs to`.

[Historically](https://github.com/openscope/openscope/blob/8110d6749e1268b002cd8af2bce7438df4c0fe28/src/assets/scripts/client/aircraft/AircraftStripView.js), `AircraftStripView.js` had `toUpperCase` on heading and destination strings, which may not have been initialized yet, hence the reported error message upon `null.toUpperCase()`.  Strip view has been considerably reworked since then; problem likely no longer exists.

**Comment by erikquinn** [comment] 2021-01-19 20:17
Definitely. This was real early into the existence of the new routing commands, which have grown to fix much more complex issues than this. So if it worked for you, I'm sure it's no longer an observable issue.

Closing.

**Closed by erikquinn** 2021-01-19 20:17 UTC
Labels: BUGFIX
