### ISSUE TITLE
Include a system to reduce game speed too..

### ISSUE THREAD

**Issue by madhursahay** [openscope/openscope#1951] opened 2022-04-25 13:49 UTC
What I have seen is that aircrafts move much faster even at normal game speed, as an ATC, it doesn't feel to realistic.
If there would be a "button" to reduce speed too........it would contribute more to realism

**Comment by Fechulo** [comment] 2022-04-25 18:23
The speed of the aircraft is accurate (as per EuroControl and FAA data), what you're probably seeing is the unrealistic refresh rate. Closing as a duplicate of #46

**Closed by Fechulo** 2022-04-25 18:23 UTC
