### ISSUE TITLE
ALTM indicator with hPa

### ISSUE THREAD

**Issue by Marcel510** [openscope/openscope#1174] opened 2018-11-07 17:27 UTC
Related #945 

Add an entry in the airport .json file to display the ALTM in hPa instead of inHg for Europe and other regions where hPa is used.

**Comment by felixscheffer** [comment] 2018-11-07 17:55
#189 - Transition Altitudes & Altimetry Units

**Comment by erikquinn** [comment] 2018-11-07 20:12
Closing as duplicate of #189

**Closed by erikquinn** 2018-11-07 20:12 UTC
Labels: enhancement
