### ISSUE TITLE
WIP Airports not appearing

### ISSUE THREAD

**Issue by jdouglas77** [openscope/openscope#999] opened 2018-06-10 07:21 UTC
Browser: Chrome/Internet Explorer

Airport:
All WIP airports

Approximate play time before issue:
Never appear

#### Issue Description
So even after i click in the settings to show wip airports there aren't any changes to the airport list
V6.1.2
Wandering if its a problem with my pc or the sim?
![image](https://user-images.githubusercontent.com/31727012/41199307-6a1158b2-6ca0-11e8-8ebc-b3cda0c8df02.png)
![image](https://user-images.githubusercontent.com/31727012/41199308-702cad5a-6ca0-11e8-9d73-21afeef7b280.png)

#### Steps to reproduce
-

**Comment by jdouglas77** [comment] 2018-06-10 07:28
![image](https://user-images.githubusercontent.com/31727012/41199351-5645f454-6ca1-11e8-8b19-205ed8397835.png)
Only the airports in bold appear in my list, even when i select wip airports on

**Comment by indianbhaji** [comment] 2018-06-10 07:33
Hi @jdouglas, I can confirm that the setting _is_ workihg as expected. There are no WIP airports anymore. The airports that you see with a double slash `//` have been disabled completely as they are absolutely no longer compatible with recent changes to the simulator.

**Comment by jdouglas77** [comment] 2018-06-10 07:35
oh that sucks, was looking to do EGLL or OMDB later...

**Comment by indianbhaji** [comment] 2018-06-10 10:20
@jdouglas77 We are looking to make those airports compatible again; they're actually in progress. @jakcharvat is working on EGLL in #986, myself on OMDB in #962. I can guarantee that OMDB will be ready for the next update, next month, so watch out for that. In the meantime, there is no issue here, so this issue will be closed. Thanks for your input though 👍

**Comment by erikquinn** [comment] 2018-06-10 21:51
Indeed it is working as intended. Though I do have one question before we move on if somebody can have a look.

It seems strange that he even has the option to "include WIP airports" in the settings. Could somebody remove that option has in fact been removed? If so, it would just be showing for him because he has a previous version in cache (this is what I suspect is going on). Just want to be sure before closing again.

**Comment by indianbhaji** [comment] 2018-06-10 21:57
@erikquinn It's still showing in 6.1.2

**Comment by erikquinn** [comment] 2018-06-10 23:13
Yikes! Just got a chance to verify, it's also showing on staging. Not going to screw with it now, but it has to go! Added #1001 for that. Re-closing this.

**Closed by erikquinn** 2018-06-10 23:13 UTC
Labels: NEEDS INVESTIGATION, invalid
