### ISSUE TITLE
Arrival Failed to Land When Locked on ILS in 5.1.0

### ISSUE THREAD

**Issue by scott-j-smith** [openscope/openscope#417] opened 2017-05-03 16:13 UTC
Hi all,

Was playing KPHX again today, and after a while I had an arriving flight that failed to land even though it was locked on the ILS well in advance.  DAL2998 flew right past the runway.  See screen shot.  This happened after about 10-15 min. and I've never seen it before.

![image](https://cloud.githubusercontent.com/assets/22403776/25670173/d7a776c0-2ff9-11e7-8dad-f764af15fe90.png)

**Comment by erikquinn** [comment] 2017-05-03 16:42
Is it possible he was simply too high? I see that it is continuing to descend, so perhaps it just couldn't descend quickly enough. There are admittedly many problems with the ILS, but I haven't seen anything like this having issues. :confused:

**Comment by scott-j-smith** [comment] 2017-05-03 17:16
Erik,

OK, yes that is possible, but I watch every flight lock on to the ILS and
it did NOT give me the warning that it was too high and deduct any points
so I assumed it was on the glide slope.

I'll play another airport I think.  Maybe this one needs to have the STAR's
reviewed.

Thanks,
Scott

**Comment by erikquinn** [comment] 2017-05-03 17:22
Hm, well part of the issue is that those warnings are apparently not working (I just checked). Created new issue for that, #419.

So I _suspect_ it was probably just a simple mistake, and there was no log message to bring your attention to it. I'll leave the issue open a few days as a reminder to keep an eye out for it. And if it doesn't recur, we'll close it and hope the problem stays away :smiley:

**Comment by scott-j-smith** [comment] 2017-05-03 17:28
Sounds like a plan!  I didn't know the warnings weren't even working.  I'll
keep my eyes open then.

**Comment by erikquinn** [comment] 2017-06-15 04:00
At this point, I think we can consider this not a new issue, as it is otherwise covered by #38 and #419.

Closing.

**Closed by erikquinn** 2017-06-15 04:00 UTC
Labels: NEEDS INVESTIGATION
