### ISSUE TITLE
RPA Go-Arounds at DCA

### ISSUE THREAD

**Issue by yield101** [openscope/openscope#1041] opened 2018-08-03 14:48 UTC
Browser: Chrome 66.0.3359.181

Airport: DCA

Approximate play time before issue: 10 mins

#### Issue Description

Flights with RPA always go around when cleared for ILS 1 landing. Shows going around within their flight plan everytime.

#### Steps to reproduce
-

**Comment by indianbhaji** [comment] 2018-08-03 17:06
Not enough information given. Altitude, STAR, speed, etc.? I can get most RPA aircraft down

**Comment by erikquinn** [comment] 2018-08-04 19:46
@yield101 To confirm a theory, what altitude were you using to get them to intercept the localizer?

**Comment by erikquinn** [comment] 2018-08-04 19:48
I ask because I am finally able to reproduce this, and I see that if I assign an altitude that is very low, the aircraft will go around when they reach a 4 mile final. This is because they are _below_ the glideslope, and not _established on_ the glideslope (as the code logic requires to continue the approach). In the case of DCA, the intercept altitude must be at least 1700 to ensure aircraft are fully established by the time they reach the FAF.

**Comment by felixscheffer** [comment] 2018-10-21 10:37
duplicate of #1084

**Closed by felixscheffer** 2018-10-21 10:37 UTC
Labels: BUGFIX
