### ISSUE TITLE
Parallel Approaches are not properly supported

### ISSUE THREAD

**Issue by owendelong** [openscope/openscope#913] opened 2018-03-02 19:44 UTC
Browser: Any

Airport: Any airport with parallel runways and simultaneous parallel approach procedures (e.g. KSFO)

Approximate play time before issue: Depends on traffic makeup and controller decisions.

#### Issue Description
Example: KSFO has simultaneous parallel ILS approaches to 28L and 28R. However, in openscope, if one has an aircraft intercept 28R from the north on a heading of 250 and has another aircraft intercept 28L from the south on a heading of 310, unless one of the aircraft is 3+ miles in trail of the other (and stays that way), at some point, they will experience a loss of separation violation according to the game.

#### Steps to reproduce
See description

#### Desired behavior
Aircraft which are established on the localizer on parallel approaches should be considered separated from each other, even if their altitudes converge and their horizontal separation is less than 3 miles.

**Comment by erikquinn** [comment] 2018-03-02 20:06
Agreed, more or less. Here's my thoughts:

Currently what it's doing is applying the rules for parallel simultaneous _dependent_ ILS approaches, correctly following the various diagonal separation minima based on the distance between the runway centerlines.

However, you are completely right: it's silly to be applying that during a huge arrival push at a place like SFO (who actually uses ILS PRM approaches, pretty neat stuff). They would be staffing a final monitor position in order to run parallel simultaneous _independent_ ILS approaches.

The truth is that some airports are set up for independents and some are not, so we somewhere have an issue outlining the need to add a way to specify whether or not a particular airport can conduct this operation. Information about whether or not we can run independent simos would be laid out in the airport guide.

I think we should elevate this task in Zube and try to get it this sprint or next.

**Comment by owendelong** [comment] 2018-03-02 20:09
Well, the information is readily available if you pick up a set of NACO charts.

**Comment by n8rzz** [comment] 2018-03-02 20:15
And @erikquinn is an air traffic controller.

I think what he is getting at is that we don't have a good way to define those separations within an aircraft file.  But it's on the roadmap, and certainly a blemish at the moment.

**Comment by owendelong** [comment] 2018-03-02 20:33
Ah... OK. 

@erikquinn -- Thanks for your service. I'm a big fan of controllers. They've been great help in times of need and even in general.

**Comment by erikquinn** [comment] 2018-03-02 22:30
@owendelong if you mean the "simultaneous approach authorized with Runway XX" in the remarks section (or whatever it's called), you may have a good point. I hadn't thought of looking at approach plates... Should check jepp charts too maybe?

My only reservation though is that (on NACO at least) it doesn't necessarily specify if it's authorizing _independent_ ILS approaches in particular (or even ILSs for that matter). And we would want to know not only if it's authorized, but if it would actually be used by that facility IRL.

**Comment by owendelong** [comment] 2018-03-03 06:27
I’m talking about whether the airport includes PRM charts. At least at the airports where I know they have simultaneous independent approaches on close runways (e.g. SFO, LAX), they publish specific PRM charts for them.

Owen

**Comment by erikquinn** [comment] 2018-03-03 18:31
I see a PRM AAUP for SFO, but none for LAX, who definitely uses simultaneous independents. But I believe the term PRM is due to the close parallels, and convergent localizers like at SFO, so it wouldn't make sense for places with regular simultaneous independent ILSs to have such a chart. :thinking_face:

**Comment by erikquinn** [comment] 2018-08-29 03:10
Related issue was #37, which has been elevated to P2 in zube, and moved into the next sprint to remind us to get to it. Left a note about this issue in that one so we can always come back here to get the additional information, but the pertinent stuff to get the issue fixed is already present in the older issue.

Labeling as discussion and closing as duplicate of #37.

**Closed by erikquinn** 2018-08-29 03:10 UTC
Labels: discussion
