### ISSUE TITLE
Aircraft do not clear the scope when uncontrolled for a bit

### ISSUE THREAD

**Issue by indianbhaji** [openscope/openscope#732] opened 2017-09-26 23:04 UTC
Browser: Chrome

Airport: CYOW (#161)

Approximate play time before issue: When browser is out of focus and plane is outside of controlzone

#### Issue Description
When aircraft are outside control zone (landed or outside of airspace) and the browser loses focus aircraft seem to freeze mid air. The scope can still be moved though

#### Steps to reproduce

1. Use the timewarp button and set it to x5
2. Clear aircraft out of your airspace, keep the browser in focus
3. The aircraft will continue moving outside the airspace but eventually they will not clear the scope and will just stay still in the air

**Comment by n8rzz** [comment] 2017-09-26 23:07
@indianbhaji And just to be clear, planes do not start moving again even after clicking within the scope window right?

**Comment by n8rzz** [comment] 2017-09-26 23:40
hmm.  I can't seem to reproduce this issue on `develop` locally.

steps I followed on `ksea`:
- timewarp 25
- clear one departure for takeoff
- wait till departure exits airspace
- move focus to editor and away from the browser
- _observe sim pause_
- return focus to browser
- _observe timewarp reset to 1 (expected) and all aircraft positions update_

**Comment by n8rzz** [comment] 2017-09-27 03:33
not sure how I did it, but I was able to reproduce this on #725.

working through the inspector, I can see that somehow the `GameController.game.focused` property does not update back to `true` on focus.  How that happens, I have no idea because the gamp loop shouldn't even be able to advance until that is marked as true and that happens within the `onFocusHandler`.

**Comment by indianbhaji** [comment] 2017-09-27 10:37
Reproduced again, but this time I did `timewarp 50` and kept the browser in focus @n8rzz @erikquinn

**Comment by indianbhaji** [comment] 2017-09-27 10:44
@n8rzz updated the reproduction steps

**Comment by indianbhaji** [comment] 2017-09-27 10:46
This is v5.5.0-BETA by the way

**Comment by n8rzz** [comment] 2017-09-27 11:15
@erikquinn you may be ready but, this now sounds like it's possibly related to the `radarTargets`

**Comment by n8rzz** [comment] 2017-09-27 11:40
```javascript
// AircraftController.aircraft_remove()
aircraft_remove = (aircraftModel) => {
    AirportController.removeAircraftFromAllRunwayQueues(aircraftModel);
    this._scopeModel.removeRadarTargetModelForAircraftModel(aircraftModel); // <-- ADD THIS LINE
    this.removeFlightNumberFromList(aircraftModel);
    this.removeAircraftModelFromList(aircraftModel);
    this._removeTransponderCodeFromUse(aircraftModel);
    this.removeAllAircraftConflictsForAircraft(aircraftModel);
    this.removeStripView(aircraftModel);
};

// ScopeModel.removeRadarTargetModelForAircraftModel()
removeRadarTargetModelForAircraftModel(aircraftModel) {
    this.radarTargetCollection.removeRadarTargetModelForAircraftModel(aircraftModel);
}
```

**Closed** 2017-09-27 22:51 UTC
Labels: BUGFIX, has pull request
